Repository 4C-multiphysics/4C, pull requests merged in 2024-12, with the labels that each got.

#35 Optimize struct handling in MulitplicativeSplitDefgradElastHyper material
  src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.cpp
  src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.hpp
  unittests/mat/4C_multiplicative_split_defgrad_elasthyper_test.cpp
Labels: team: material

#112 Move the Dockerfile for the dependencies image
  .github/actions/compute-and-check-dependencies-hash/action.yml
  .github/workflows/buildtest.yml
  .github/workflows/checkcode.yml
  .github/workflows/docker.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly_tests.yml
  docker/README.md
  docker/dependencies/Dockerfile
  docker/dependencies/compute_dependencies_hash.sh
  tests/testconfig/.gitlab-ci.yml
  utilities/four_c_utils/src/four_c_utils/check_workflow_dependencies_hash.py
Labels: team: infrastructure

#115 Migrate porofluidmulti to vtk based output
  apps/post_processor/4C_post_processor.cpp
  apps/post_processor/4C_post_processor_single_field_writers.cpp
  apps/post_processor/4C_post_processor_single_field_writers.hpp
  src/porofluidmultiphase/4C_porofluidmultiphase_timint_implicit.cpp
  src/porofluidmultiphase/4C_porofluidmultiphase_timint_implicit.hpp
  src/porofluidmultiphase/4C_porofluidmultiphase_timint_ost.cpp
  tests/input_files/poromultielastscatra_2D_quad4_tumor.dat
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-porofluid.pvd
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00000-0.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00000-1.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00000-2.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00000.pvtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00002-0.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00002-1.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00002-2.vtu
  tests/input_files/ref/poromultielastscatra_2D_quad4_tumor-vtk-files/porofluid-00002.pvtu
  tests/list_of_tests.cmake
Labels: taskforce: output

#126 Add a missing MPI include when ArborX is off
  src/core/fem/src/geometric_search/4C_fem_geometric_search_utils.hpp
Labels: priority: high, type: bug report

#124 Update LNM default compiler to GCC 13.2
  presets/lnm/workstation/CMakePresets.json
Labels: team: infrastructure

#123 Only push docker images in workflows when they are run from the base repo
  .github/workflows/docker.yml
  .github/workflows/docker_prebuilt_4c.yml
Labels: team: infrastructure

#102 Improve substepping implementation in InelasticDefgradTransvIsotropElastViscoplast
  src/mat/4C_mat_inelastic_defgrad_factors.cpp
  src/mat/4C_mat_inelastic_defgrad_factors.hpp
  src/mat/4C_mat_inelastic_defgrad_factors_service.hpp
  src/mat/vplast/4C_mat_vplast_law.hpp
  src/mat/vplast/4C_mat_vplast_reform_johnsoncook.cpp
  src/mat/vplast/4C_mat_vplast_reform_johnsoncook.hpp
  unittests/mat/4C_inelastic_defgrad_factors_test.cpp
  unittests/mat/vplast/4C_vplast_reform_johnsoncook_test.cpp
Labels: team: material

#133 Remove unused print functions
  src/core/fem/src/condition/4C_fem_condition_definition.cpp
  src/core/fem/src/condition/4C_fem_condition_definition.hpp
  src/core/io/src/4C_io_linecomponent.cpp
  src/core/io/src/4C_io_linecomponent.hpp
  src/inpar/4C_inpar_validconditions.cpp
  src/inpar/4C_inpar_validmaterials.cpp
Labels: type: clean code

#131 Quick fix for the material evaluate calls in the case of InelasticDefgradTransvIsotropElastViscoplast
  src/mat/4C_mat_inelastic_defgrad_factors.cpp
  src/mat/4C_mat_inelastic_defgrad_factors.hpp
  src/mat/4C_mat_inelastic_defgrad_factors_service.hpp
Labels: team: material

#150 Add error on not supported output case
  src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp
Labels: taskforce: output

#156 Increase number of chunks for coverage workflow
  .github/workflows/coverage.yml
Labels: priority: high

#168 Fix wrong input para name in partitioned poroelast amd add test
  src/poroelast/4C_poroelast_partitioned.cpp
  tests/input_files/new_solidporo_pressure_velocity_based_ele_3D_hex8_stat_part.dat
  tests/list_of_tests.cmake
Labels: team: poro

#165 Reimplement LineDefinition as a more powerful InputSpec
  src/core/io/src/4C_io_input_parameter_container.cpp
  src/core/io/src/4C_io_input_parameter_container.hpp
  src/core/io/src/4C_io_input_spec.cpp
  src/core/io/src/4C_io_input_spec.hpp
  src/core/io/src/4C_io_input_spec_builders.cpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_linedefinition.cpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  src/core/io/tests/4C_io_linedefinition_test.cpp
Labels: team: input

#178 Fix a bug where multiscale mat is freed too late
  src/mat/4C_mat_micromaterialgp_static.cpp
  src/mat/4C_mat_micromaterialgp_static.hpp
  tests/input_files/sohex8_multiscale_micro1.mat
  tests/input_files/sohex8_stress_response_result_test.dat
Labels: type: enhancement
