Repository 4C-multiphysics/4C, pull requests merged in 2025-05, with the labels that each got.

#729 Remove INVALID_TEMPLATE_QUALIFIER
  src/adapter/4C_adapter_str_structure_new.cpp
  src/scatra_ele/4C_scatra_ele_calc_lsreinit.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_group_prepostoperator.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem_prepostoperator.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linesearch_prepostoperator.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Labels: type: clean code

#727 CMake: ensure that cache variables are set
  CMakeLists.txt
  cmake/functions/four_c_auto_define_tests.cmake
  cmake/functions/four_c_configure_dependency.cmake
  cmake/functions/four_c_process_global_option.cmake
  cmake/functions/four_c_testing_functions.cmake
  cmake/setup_tests.cmake
Labels: team: infrastructure

#730 Clean scatra set state methods
  src/adapter/4C_adapter_scatra_fluid_coupling_algorithm.cpp
  src/elch/4C_elch_dyn.cpp
  src/elch/4C_elch_moving_boundary_algorithm.cpp
  src/fs3i/4C_fs3i_fps3i_partitioned.cpp
  src/fs3i/4C_fs3i_partitioned.cpp
  src/fs3i/4C_fs3i_partitioned_2wc.cpp
  src/levelset/4C_levelset_algorithm.hpp
  src/levelset/4C_levelset_algorithm_utils.cpp
  src/loma/4C_loma_algorithm.cpp
  src/loma/4C_loma_dyn.cpp
  src/mat/4C_mat_scatra_multiscale_gp.cpp
  src/poroelast_scatra/4C_poroelast_scatra_base.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_base.cpp
  src/scatra/4C_scatra_algorithm.cpp
  src/scatra/4C_scatra_cardiac_monodomain_dyn.cpp
  src/scatra/4C_scatra_dyn.cpp
  src/scatra/4C_scatra_timint_elch_scl.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/scatra/4C_scatra_timint_implicit.hpp
  src/ssi/4C_ssi_base.cpp
  src/ssi/4C_ssi_base.hpp
  src/ssi/4C_ssi_coupling.cpp
  src/ssi/4C_ssi_coupling.hpp
  src/ssi/4C_ssi_monolithic.cpp
  src/ssi/4C_ssi_partitioned_1wc.cpp
  src/ssi/4C_ssi_partitioned_2wc.cpp
  src/ssti/4C_ssti_algorithm.cpp
  src/ssti/4C_ssti_algorithm.hpp
  src/sti/4C_sti_algorithm.cpp
  src/sti/4C_sti_dyn.cpp
Labels: type: clean code, team: scatra

#732 Make the developer docs nicer
  doc/documentation/CMakeLists.txt
  doc/documentation/src/_static/html_extensions.css
  doc/documentation/src/developer_guide/codingguidelines.rst
  doc/documentation/src/developer_guide/debugging_profiling.rst
  doc/documentation/src/developer_guide/developer_addedinformation.rst
  doc/documentation/src/developer_guide/developer_dirstructure.rst
  doc/documentation/src/developer_guide/developmentguide.rst
  doc/documentation/src/developer_guide/time_monitoring.rst
Labels: team: infrastructure

#734 Make a check in scatra microscale independent of node numbering
  src/mat/4C_mat_scatra_multiscale_gp.cpp
Labels: team: scatra

#740 Remove a NURBS input debug print
  src/core/io/src/4C_io_input_file_utils.cpp
Labels: type: clean code

#738 Remove some unused Condition and Discretization evaluation code
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils.hpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_dbc.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp
Labels: type: clean code, team: discretization

#742 Remove unused Dirchlet flags from LocationVector
  src/ale/4C_ale.cpp
  src/art_net/4C_art_net_impl_stationary.cpp
  src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp
  src/core/fem/src/general/element/4C_fem_general_element.cpp
  src/core/fem/src/general/element/4C_fem_general_element.hpp
  src/core/fem/src/general/utils/4C_fem_general_l2_projection.cpp
  src/core/fem/src/general/utils/4C_fem_general_utils_superconvergent_patch_recovery.cpp
  src/core/io/src/4C_io_gmsh.cpp
  src/deal_ii/src/4C_deal_ii_vector_conversion.cpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/fluid/4C_fluid_timint_hdg.cpp
  src/fluid/4C_fluid_timint_hdg_weak_comp.cpp
  src/fluid/4C_fluid_timint_stat_hdg.cpp
  src/fluid_ele/4C_fluid_ele.hpp
  src/fluid_ele/4C_fluid_ele_boundary_evaluate.cpp
  src/fluid_ele/4C_fluid_ele_calc_hdg.cpp
  src/fluid_ele/4C_fluid_ele_calc_hdg_weak_comp.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem.cpp
  src/fluid_ele/4C_fluid_ele_poro.hpp
  src/fluid_ele/4C_fluid_ele_poro_boundary_evaluate.cpp
  src/fluid_ele/4C_fluid_ele_xwall.hpp
  src/fluid_ele/4C_fluid_ele_xwall_boundary.cpp
  src/fluid_turbulence/4C_fluid_turbulence_boxfilter.cpp
  src/fluid_turbulence/4C_fluid_turbulence_dyn_smag.cpp
  src/fluid_turbulence/4C_fluid_turbulence_hit_forcing.cpp
  src/fluid_turbulence/4C_fluid_turbulence_hit_initial_field.cpp
  src/fluid_xfluid/4C_fluid_xfluid.cpp
  src/fluid_xfluid/4C_fluid_xfluid_fluid.cpp
  src/fluid_xfluid/4C_fluid_xfluid_outputservice.cpp
  src/levelset/4C_levelset_algorithm_utils.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_pair.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_evaluate.cpp
  src/scatra/4C_scatra_timint_cardiac_monodomain_scheme_hdg.cpp
  src/scatra/4C_scatra_timint_elch.cpp
  src/scatra/4C_scatra_timint_hdg.cpp
  src/scatra/4C_scatra_timint_implicit_service.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
  src/scatra_ele/4C_scatra_ele.hpp
  src/scatra_ele/4C_scatra_ele_boundary_calc.cpp
  src/scatra_ele/4C_scatra_ele_boundary_evaluate.cpp
  src/scatra_ele/4C_scatra_ele_hdg.cpp
  src/scatra_ele/4C_scatra_ele_hdg.hpp
  src/stru_multi/4C_stru_multi_microstatic.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp
  src/xfem/4C_xfem_coupling_mesh.cpp
  src/xfem/4C_xfem_interface_utils.cpp
  src/xfem/4C_xfem_utils.cpp
  src/xfem/4C_xfem_xfluid_contact_communicator.cpp
  src/xfem/4C_xfem_xfluid_timeInt_base.cpp
  src/xfem/4C_xfem_xfluid_timeInt_std_SemiLagrange.cpp
Labels: type: clean code

#744 Fix a few poor names in DofSets
  src/cardiovascular0d/4C_cardiovascular0d_dofset.cpp
  src/constraint/4C_constraint_dofset.cpp
  src/core/fem/src/dofset/4C_fem_dofset.cpp
  src/core/fem/src/dofset/4C_fem_dofset_base.cpp
  src/core/fem/src/dofset/4C_fem_dofset_base.hpp
  src/core/fem/src/dofset/4C_fem_dofset_definedmapping_wrapper.hpp
  src/core/fem/src/dofset/4C_fem_dofset_gidbased_wrapper.hpp
  src/core/fem/src/dofset/4C_fem_dofset_independent.cpp
  src/core/fem/src/dofset/4C_fem_dofset_independent.hpp
  src/core/fem/src/dofset/4C_fem_dofset_interface.hpp
  src/core/fem/src/dofset/4C_fem_dofset_merged_wrapper.hpp
  src/core/fem/src/dofset/4C_fem_dofset_predefineddofnumber.hpp
  src/core/fem/src/dofset/4C_fem_dofset_proxy.cpp
  src/core/fem/src/dofset/4C_fem_dofset_proxy.hpp
Labels: type: clean code

#745 Remove unused code in Condition utils
  src/core/fem/src/condition/4C_fem_condition_utils.cpp
  src/core/fem/src/condition/4C_fem_condition_utils.hpp
  src/core/fem/src/general/utils/4C_fem_general_utils_createdis.hpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/coupling/src/adapter/4C_coupling_adapter.hpp
  src/scatra/4C_scatra_utils.cpp
  src/xfem/4C_xfem_discretization_utils.cpp
  src/xfem/4C_xfem_discretization_utils.hpp
Labels: type: clean code, team: infrastructure

#748 Remove RedAirwayTissue problem type
  apps/global_full/4C_global_full_cal_control.cpp
  apps/post_processor/4C_post_processor.cpp
  doc/documentation/src/analysis_guide/problemtypes.rst
  doc/removed_code/major_changes.txt
  src/adapter/4C_adapter_str_redairway.cpp
  src/adapter/4C_adapter_str_redairway.hpp
  src/adapter/4C_adapter_str_structure.cpp
  src/adapter/4C_adapter_str_structure_new.cpp
  src/core/legacy_enum_definitions/4C_legacy_enum_definitions_conditions.cpp
  src/core/legacy_enum_definitions/4C_legacy_enum_definitions_problem_type.hpp
  src/global_data/4C_global_data_read.cpp
  src/inpar/4C_inpar_problemtype.cpp
  src/red_airways/4C_red_airways_dyn_drt.cpp
  src/red_airways/4C_red_airways_dyn_drt.hpp
  src/red_airways/4C_red_airways_implicitintegration.cpp
  src/red_airways/4C_red_airways_implicitintegration.hpp
  src/red_airways/4C_red_airways_tissue.cpp
  src/red_airways/4C_red_airways_tissue.hpp
  tests/input_files/red_airway_tissue_coupling.dat
  tests/list_of_tests.cmake
Labels: team: reduced_fluid_models, breaking change

#747 CMake: set cache variables for MathJax in Doxygen
  doc/doxygen/CMakeLists.txt
Labels: team: infrastructure

#750 Clean up internals of conditions in Discretization
  src/core/fem/src/condition/4C_fem_condition.hpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_conditions.cpp
  src/core/legacy_enum_definitions/4C_legacy_enum_definitions_conditions.cpp
  src/core/legacy_enum_definitions/4C_legacy_enum_definitions_conditions.hpp
  src/red_airways/4C_red_airways_input.cpp
Labels: type: clean code, team: discretization

#752 Port contact tutorial to direct exodus input
  doc/documentation/src/tutorial_templates/tutorial_contact_3d.md.j2
  tests/framework-test/tutorial_contact_3d.4C.yaml
  tests/framework-test/tutorial_contact_3d.bc
  tests/framework-test/tutorial_contact_3d.head
  tests/input_files/contact3D_exodus_in.exo
  tests/list_of_tests.cmake
Labels: team: input

#758 Minor improvement to LinAlg::View
  src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_view.hpp
  src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp
  src/structure/4C_structure_timint_noxlinsys.cpp
Labels: type: clean code

#757 Port fluid tutorial to direct exodus input
  doc/documentation/src/tutorial_templates/tut_fluid_preexo.rst.j2
  tests/framework-test/tutorial_fluid.4C.yaml
  tests/input_files/fluid_exodus_in.exo
  tests/list_of_tests.cmake
Labels: team: input

#767 Port 2D FSI tutorial to direct exodus input
  doc/documentation/src/tutorial_templates/tut_fsi_preexo_2d.rst.j2
  src/core/io/src/4C_io_exodus.hpp
  src/core/io/src/4C_io_meshreader.cpp
  tests/framework-test/tutorial_fluid.bc
  tests/framework-test/tutorial_fluid.head
  tests/framework-test/tutorial_fsi.bc
  tests/framework-test/tutorial_fsi_2d.4C.yaml
  tests/framework-test/tutorial_fsi_2d.e
  tests/framework-test/tutorial_fsi_2d.jou
  tests/list_of_tests.cmake
Labels: type: clean code, team: input

#768 Remove an unused fluid boundary function
  src/fluid_ele/4C_fluid_ele_action.hpp
  src/fluid_ele/4C_fluid_ele_boundary_calc.cpp
  src/fluid_ele/4C_fluid_ele_boundary_calc.hpp
  src/fluid_ele/4C_fluid_ele_boundary_evaluate.cpp
Labels: team: discretization

#756 Simplify ConditionSelector classes into a function
  src/ale/4C_ale_utils_mapextractor.cpp
  src/core/fem/src/condition/4C_fem_condition_selector.cpp
  src/core/fem/src/condition/4C_fem_condition_selector.hpp
  src/core/fem/src/condition/4C_fem_condition_utils.cpp
  src/core/fem/src/condition/4C_fem_condition_utils.hpp
  src/fluid/4C_fluid_utils_mapextractor.cpp
  src/fpsi/4C_fpsi_coupling.cpp
  src/fpsi/4C_fpsi_utils.cpp
  src/fs3i/4C_fs3i_fps3i_partitioned.cpp
  src/fs3i/4C_fs3i_partitioned.cpp
  src/fsi_xfem/4C_fsi_xfem_coupling_comm_manager.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_nodebased.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/structure/4C_structure_aux.cpp
Labels: type: clean code, team: discretization

#769 Major rework of the solid-state battery tutorial
  doc/documentation/src/_assets/tutorial-battery-geometry.png
  doc/documentation/src/_assets/tutorial_battery.jpg
  doc/documentation/src/tutorial_templates/tut_battery.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_battery.md.j2
  doc/documentation/src/tutorial_templates/tutorials.rst
  tests/framework-test/tutorial_battery.4C.yaml
  tests/framework-test/tutorial_battery.bc
  tests/framework-test/tutorial_battery.head
  tests/list_of_tests.cmake
Labels: team: input

#772 Port 3D FSI tutorial to direct EXODUS input
  doc/documentation/src/tutorial_templates/tut_fsi_preexo.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_contact_3d.md.j2
  doc/documentation/src/tutorial_templates/tutorial_fluid.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_fsi_2d.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_fsi_3d.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_introduction.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_solid.rst.j2
  doc/documentation/src/tutorial_templates/tutorials.rst
  tests/framework-test/tutorial_fsi_3d.4C.yaml
  tests/framework-test/tutorial_fsi_3d.bc
  tests/framework-test/tutorial_fsi_3d.head
  tests/list_of_tests.cmake
Labels: team: fsi, team: input

#774 Remove pre_exodus
  CMakeLists.txt
  apps/CMakeLists.txt
  apps/pre_exodus/4C_pre_exodus.cpp
  apps/pre_exodus/4C_pre_exodus_readbc.cpp
  apps/pre_exodus/4C_pre_exodus_readbc.hpp
  apps/pre_exodus/4C_pre_exodus_validate.cpp
  apps/pre_exodus/4C_pre_exodus_validate.hpp
  apps/pre_exodus/4C_pre_exodus_writedat.cpp
  apps/pre_exodus/4C_pre_exodus_writedat.hpp
  apps/pre_exodus/CMakeLists.txt
  cmake/functions/four_c_testing_functions.cmake
  doc/documentation/CMakeLists.txt
  doc/documentation/src/analysis_guide/boundaryconditions.rst
  doc/documentation/src/analysis_guide/preprocessing.rst
  doc/documentation/src/installation/installation.rst
  doc/documentation/src/tutorial_templates/tutorial_fsi_2d.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_fsi_3d.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_introduction.rst.j2
  doc/documentation/src/tutorial_templates/tutorial_solid.rst.j2
  doc/documentation/src/tutorial_templates/tutorials.rst
  src/core/io/src/4C_io.cpp
  tests/input_files/embeddedmesh_cut_bar_under_torsion_one_element.dat
  tests/input_files/embeddedmesh_cut_integrate_bar_hex8_ele_1.dat
  tests/input_files/embeddedmesh_two_blocks_hex_hex_5x5.dat
  tests/list_of_tests.cmake
  tests/pre_processing_test/pre_exo_cube.bc
  tests/pre_processing_test/pre_exo_cube.e
  tests/tutorials/tutorial_battery.4C.yaml
  tests/tutorials/tutorial_battery.e
  tests/tutorials/tutorial_battery.jou
  tests/tutorials/tutorial_contact_3d.4C.yaml
  tests/tutorials/tutorial_contact_3d.e
  tests/tutorials/tutorial_contact_3d.jou
  tests/tutorials/tutorial_fluid.4C.yaml
  tests/tutorials/tutorial_fluid.e
  tests/tutorials/tutorial_fluid.jou
  tests/tutorials/tutorial_fsi_2d.4C.yaml
  tests/tutorials/tutorial_fsi_2d.e
  tests/tutorials/tutorial_fsi_2d.jou
  tests/tutorials/tutorial_fsi_3d.4C.yaml
  tests/tutorials/tutorial_fsi_3d.e
  tests/tutorials/tutorial_fsi_3d.jou
  tests/tutorials/tutorial_solid.4C.yaml
  tests/tutorials/tutorial_solid.jou
  tests/tutorials/tutorial_solid_geo.e
Labels: team: input, breaking change

#782 Remove unused features from Exodus::Mesh
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/src/4C_io_exodus.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/tests/4C_io_exodus_test.cpp
  src/global_data/4C_global_data_read.cpp
Labels: type: clean code, team: input

#784 Add Box type for heap-allocated values
  src/core/utils/src/stl_extension/4C_utils_box.hpp
  src/solid_3D_ele/4C_solid_3D_ele_factory_lib.hpp
Labels: team: infrastructure

#790 Remove calls to replace_map
  src/mortar/4C_mortar_utils.cpp
  src/mortar/4C_mortar_utils.hpp
  src/ssi/4C_ssi_partitioned_1wc.cpp
  src/timestepping/4C_timestepping_mstep.hpp
Labels: taskforce: tpetra

#796 Move ElCh input to module
  src/adapter/4C_adapter_fld_base_algorithm.cpp
  src/elch/4C_elch_dyn.cpp
  src/elch/4C_elch_input.cpp
  src/elch/4C_elch_input.hpp
  src/elch/4C_elch_moving_boundary_algorithm.cpp
  src/global_legacy_module/4C_global_legacy_module_validconditions.cpp
  src/global_legacy_module/4C_global_legacy_module_validparameters.cpp
  src/inpar/4C_inpar_elch.hpp
  src/scatra/4C_scatra_timint_elch.cpp
  src/scatra/4C_scatra_timint_elch.hpp
  src/scatra/4C_scatra_timint_elch_scl.cpp
  src/scatra/4C_scatra_timint_elch_scl.hpp
  src/scatra/4C_scatra_timint_elch_service.cpp
  src/scatra/4C_scatra_timint_elch_service.hpp
  src/scatra/4C_scatra_timint_meshtying_strategy_fluid_elch.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i_elch.cpp
  src/scatra/CMakeLists.txt
  src/scatra_ele/4C_scatra_ele_boundary_calc.hpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch_NP.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch_electrode.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch_electrode_growth.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc_elch_electrode_sti_thermo.cpp
  src/scatra_ele/4C_scatra_ele_calc_elch.hpp
  src/scatra_ele/4C_scatra_ele_calc_elch_NP.cpp
  src/scatra_ele/4C_scatra_ele_calc_elch_NP.hpp
  src/scatra_ele/4C_scatra_ele_calc_elch_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_calc_elch_diffcond.hpp
  src/scatra_ele/4C_scatra_ele_calc_elch_electrode.hpp
  src/scatra_ele/4C_scatra_ele_calc_elch_scl.cpp
  src/scatra_ele/4C_scatra_ele_calc_elch_scl.hpp
  src/scatra_ele/4C_scatra_ele_calc_service_elch.cpp
  src/scatra_ele/4C_scatra_ele_calc_service_elch_NP.cpp
  src/scatra_ele/4C_scatra_ele_calc_service_elch_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_calc_service_elch_electrode.cpp
  src/scatra_ele/4C_scatra_ele_calc_sti_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_calc_sti_electrode.hpp
  src/scatra_ele/4C_scatra_ele_parameter_elch.cpp
  src/scatra_ele/4C_scatra_ele_parameter_elch.hpp
  src/scatra_ele/4C_scatra_ele_parameter_elch_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_utils_elch.cpp
  src/scatra_ele/4C_scatra_ele_utils_elch.hpp
  src/scatra_ele/4C_scatra_ele_utils_elch_diffcond.cpp
  src/scatra_ele/4C_scatra_ele_utils_elch_diffcond.hpp
  src/scatra_ele/4C_scatra_ele_utils_elch_scl.cpp
  src/scatra_ele/4C_scatra_ele_utils_elch_scl.hpp
  src/ssi/4C_ssi_monolithic.cpp
Labels: taskforce: modularization

#787 Enable LinAlg::View for Map
  src/core/linalg/src/sparse/4C_linalg_map.cpp
  src/core/linalg/src/sparse/4C_linalg_map.hpp
  src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_sparsematrixbase.hpp
  src/core/linalg/src/sparse/4C_linalg_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_view.hpp
  src/core/utils/src/stl_extension/4C_utils_owner_or_view.hpp
Labels: taskforce: tpetra

#800 Remove unused DebugWriter for FSI problems
  src/fpsi/4C_fpsi_monolithic.hpp
  src/fpsi/4C_fpsi_monolithic_plain.cpp
  src/fsi/src/monolithic/4C_fsi_monolithic.cpp
  src/fsi/src/monolithic/4C_fsi_monolithic.hpp
  src/fsi/src/monolithic/4C_fsi_monolithic_nonox.cpp
  src/fsi/src/monolithic/4C_fsi_monolithic_nonox.hpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_fluidfluidmonolithic_fluidsplit_nonox.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_fluidfluidmonolithic_structuresplit_nonox.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_monolithicfluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_monolithicstructuresplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_mortarmonolithic_fluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_mortarmonolithic_fluidsplit_sp.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_mortarmonolithic_structuresplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_slidingmonolithic_fluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_slidingmonolithic_structuresplit.cpp
  src/fsi/src/partitioned/4C_fsi_partitioned.cpp
  src/fsi/src/partitioned/4C_fsi_partitioned.hpp
  src/fsi/src/partitioned/model_evaluator/4C_fsi_dirichletneumann.cpp
  src/fsi/src/partitioned/model_evaluator/4C_fsi_dirichletneumann_disp.cpp
  src/fsi/src/partitioned/model_evaluator/4C_fsi_dirichletneumann_volcoupl.cpp
  src/fsi/src/partitioned/model_evaluator/4C_fsi_dirichletneumannslideale.cpp
  src/fsi/src/utils/4C_fsi_debugwriter.cpp
  src/fsi/src/utils/4C_fsi_debugwriter.hpp
  src/fsi_xfem/4C_fsi_xfem_monolithic.cpp
  src/fsi_xfem/4C_fsi_xfem_monolithic.hpp
  src/inpar/4C_inpar_fsi.cpp
  tests/input_files/fs3i_mult_scalar_windkessel_reac.dat
  tests/input_files/fsci_simp_salz_syst.dat
  tests/input_files/tfsi_plate.dat
Labels: team: fsi, breaking change

#797 Migrate commit-msg hook to pre-commit
  .pre-commit-config.yaml
  utilities/code_checks/check_venv
  utilities/code_checks/commit-msg
  utilities/set_up_dev_env.sh
Labels: team: infrastructure

#804 Use correct English possessive pronouns
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.hpp
  src/constraint/4C_constraint_multipointconstraint2.cpp
  src/constraint/4C_constraint_multipointconstraint3.cpp
  src/constraint/4C_constraint_multipointconstraint3penalty.cpp
  src/core/binstrategy/4C_binstrategy.cpp
  src/core/binstrategy/4C_binstrategy_utils.cpp
  src/core/fem/src/condition/4C_fem_condition_periodic.cpp
  src/core/fem/src/condition/4C_fem_condition_periodic.hpp
  src/core/geometric_search/src/4C_geometric_search_matchingoctree.cpp
  src/core/geometric_search/src/4C_geometric_search_matchingoctree.hpp
  src/core/io/src/legacy/4C_io_legacy_table_iter.cpp
  src/cut/4C_cut_element.hpp
  src/cut/4C_cut_tetmesh.cpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem_coupling_impl.hpp
  src/fsi_xfem/4C_fsi_xfem_coupling_comm_manager.cpp
  src/mat/4C_mat_damage.cpp
  src/mixture/4C_mixture_rule.hpp
  src/structure/4C_structure_timint_impl.cpp
  src/tsi/4C_tsi_partitioned.cpp
Labels: type: clean code

#805 Remove unused level set function
  src/levelset/4C_levelset_algorithm.hpp
  src/levelset/4C_levelset_algorithm_utils.cpp
Labels: type: clean code

#806 Add missing include for older Trilinos versions
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_nox.cpp
Labels: priority: high, type: bug report

#793 Rework of ssi monolithic meshtying strategy
  src/ssi/4C_ssi_dyn.cpp
  src/ssi/4C_ssi_monolithic.cpp
  src/ssi/4C_ssi_monolithic.hpp
  src/ssi/4C_ssi_monolithic_meshtying_strategy.cpp
  src/ssi/4C_ssi_monolithic_meshtying_strategy.hpp
Labels: team: scatra

#816 Cleanup of scatra timint implicit
  src/adapter/4C_adapter_scatra_interface.hpp
  src/adapter/4C_adapter_scatra_wrapper.hpp
  src/fs3i/4C_fs3i.cpp
  src/fs3i/4C_fs3i.hpp
  src/levelset/4C_levelset_algorithm.cpp
  src/levelset/4C_levelset_algorithm.hpp
  src/levelset/4C_levelset_algorithm_reinit.cpp
  src/scatra/4C_scatra_timint_elch.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/scatra/4C_scatra_timint_implicit.hpp
  src/scatra/4C_scatra_timint_implicit_service.cpp
  src/ssi/4C_ssi_base.cpp
  src/ssi/4C_ssi_base.hpp
  src/sti/4C_sti_algorithm.cpp
  src/sti/4C_sti_monolithic.cpp
  src/sti/4C_sti_monolithic.hpp
  src/sti/4C_sti_partitioned.cpp
Labels: team: scatra

#821 Avoid include cycles
  .pre-commit-config.yaml
  src/cut/4C_cut_kernel.hpp
  src/poroelast/4C_poroelast_utils_setup.hpp
  utilities/four_c_utils/pyproject.toml
  utilities/four_c_utils/src/four_c_utils/check_includes_for_cycles.py
  utilities/requirements.txt
Labels: taskforce: modularization

#826 Remove `shared_ptr` methods from `LinAlg::Vector` interface
  src/adapter/4C_adapter_str_constr_merged.cpp
  src/adapter/4C_adapter_str_fsiwrapper.cpp
  src/adapter/4C_adapter_str_structure.hpp
  src/adapter/4C_adapter_str_structure_new.hpp
  src/adapter/4C_adapter_str_wrapper.hpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_visualization_output_writer.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_visualization_output_writer_contact.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_visualization_output_writer_utils.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_visualization_output_writer_utils.hpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_volume_meshtying_visualization_output_writer.cpp
  src/constraint/4C_constraint_lagpenconstraint_noxinterface.cpp
  src/contact/4C_contact_lagrange_strategy_wear.cpp
  src/contact/4C_contact_meshtying_noxinterface.cpp
  src/contact/4C_contact_noxinterface.cpp
  src/core/fem/src/general/utils/4C_fem_general_l2_projection.cpp
  src/core/io/src/4C_io.cpp
  src/core/linalg/src/sparse/4C_linalg_vector.cpp
  src/core/linalg/src/sparse/4C_linalg_vector.hpp
  src/core/linalg/tests/4C_linalg_map_test.np2.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp
  src/core/rebalance/src/4C_rebalance_graph_based.cpp
  src/ehl/4C_ehl_base.cpp
  src/fs3i/4C_fs3i_biofilm_fsi.cpp
  src/fsi/src/monolithic/4C_fsi_monolithic.cpp
  src/fsi/src/partitioned/4C_fsi_partitioned.cpp
  src/fsi/src/partitioned/model_evaluator/4C_fsi_str_model_evaluator_partitioned.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_ptc.cpp
  src/stru_multi/4C_stru_multi_microstatic.cpp
  src/structure/4C_structure_timint.cpp
  src/structure/4C_structure_timint.hpp
  src/structure/4C_structure_timint_impl_nox.cpp
  src/structure_new/src/4C_structure_new_integrator.cpp
  src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp
  src/structure_new/src/implicit/4C_structure_new_impl_statics.cpp
  src/structure_new/src/implicit/4C_structure_new_timint_implicit.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.hpp
  src/xfem/4C_xfem_xfield_field_coupling.cpp
Labels: taskforce: tpetra

#823 Remove unnecessary Map instantiations
  src/core/comm/src/4C_comm_utils.cpp
  src/core/linalg/src/sparse/4C_linalg_krylov_projector.cpp
  src/fluid/4C_fluid_timint_genalpha.cpp
  src/post/4C_post_ensight_writer.cpp
Labels: type: clean code

#795 Remove more `get_condition` from Node class
  src/beam3/4C_beam3_discretization_runtime_vtu_writer.cpp
  src/beaminteraction/src/4C_beaminteraction_calc_utils.cpp
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp
  src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_mortar_manager.cpp
  src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_utils.cpp
  src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_utils.hpp
  src/core/fem/src/condition/4C_fem_condition_utils.cpp
  src/core/fem/src/condition/4C_fem_condition_utils.hpp
  src/core/fem/src/dofset/4C_fem_dofset_merged_wrapper.cpp
  src/core/rebalance/src/4C_rebalance_binning_based.cpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_linebased.cpp
  src/reduced_lung/4C_reduced_lung_main.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
  src/scatra/4C_scatra_utils.cpp
  src/ssi/4C_ssi_utils.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp
  src/xfem/4C_xfem_coupling_mesh.cpp
  src/xfem/4C_xfem_coupling_mesh.hpp
Labels: team: discretization
