Repository 4C-multiphysics/4C, pull requests merged in 2025-03, with the labels that each got.

#469 InputSpec: new selection for common use case
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
Labels: team: input

#476 Add CMake option FOUR_C_ENABLE_METADATA_GENERATION
  apps/global_full/CMakeLists.txt
  cmake/setup_global_options.cmake
Labels: type: enhancement, team: infrastructure

#474 Add magic_enum dependency and allow parameter to take enums
  CMakeLists.txt
  cmake/configure/configure_magic_enum.cmake
  cmake/setup_install.cmake
  cmake/templates/4CConfig.cmake.in
  cmake/templates/4CSettings.cmake.in
  cmake/templates/4CTargets.cmake.in
  cmake/templates/magic_enum.cmake.in
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_input_types.hpp
  src/core/io/src/4C_io_value_parser.hpp
  src/core/io/src/4C_io_yaml.cpp
  src/core/io/src/4C_io_yaml.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  src/global_legacy_module/4C_global_legacy_module.cpp
  utilities/create_json_schema.py
  utilities/metadata_utils.py
Labels: team: infrastructure

#486 Update coding guidelines in docs
  doc/readthedocs/codingguidelines.rst
Labels: team: infrastructure

#489 Remove MaterialDefinition and use InputSpec
  apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp
  apps/create_rtdfiles/4C_create_rtdfiles_utils.hpp
  apps/create_rtdfiles/4C_create_rtdfiles_wrapper.cpp
  src/global_data/4C_global_data.cpp
  src/global_data/4C_global_data_read.cpp
  src/global_legacy_module/4C_global_legacy_module.cpp
  src/global_legacy_module/4C_global_legacy_module_validmaterials.cpp
  src/global_legacy_module/4C_global_legacy_module_validmaterials.hpp
  src/mat/4C_mat_materialdefinition.cpp
  src/mat/4C_mat_materialdefinition.hpp
Labels: type: clean code, team: input

#491 Remove old input interfaces for int
  src/ale/4C_ale_input.cpp
  src/beamcontact/4C_beamcontact_input.cpp
  src/cut/4C_cut_input.cpp
  src/inpar/4C_inpar_IO_monitor_structure_dbc.cpp
  src/inpar/4C_inpar_IO_runtime_output.cpp
  src/inpar/4C_inpar_IO_runtime_output_structure_beams.cpp
  src/inpar/4C_inpar_IO_runtime_vtp_output_structure.cpp
  src/inpar/4C_inpar_beam_to_solid.cpp
  src/inpar/4C_inpar_beampotential.cpp
  src/inpar/4C_inpar_binningstrategy.cpp
  src/inpar/4C_inpar_bio.cpp
  src/inpar/4C_inpar_cardiac_monodomain.cpp
  src/inpar/4C_inpar_cardiovascular0d.cpp
  src/inpar/4C_inpar_contact.cpp
  src/inpar/4C_inpar_ehl.cpp
  src/inpar/4C_inpar_elch.cpp
  src/inpar/4C_inpar_elemag.cpp
  src/inpar/4C_inpar_fbi.cpp
  src/inpar/4C_inpar_fluid.cpp
  src/inpar/4C_inpar_fpsi.cpp
  src/inpar/4C_inpar_fs3i.cpp
  src/inpar/4C_inpar_fsi.cpp
  src/inpar/4C_inpar_geometry_pair.cpp
  src/inpar/4C_inpar_io.cpp
  src/inpar/4C_inpar_levelset.cpp
  src/inpar/4C_inpar_mortar.cpp
  src/inpar/4C_inpar_particle.cpp
  src/inpar/4C_inpar_pasi.cpp
  src/inpar/4C_inpar_poroelast.cpp
  src/inpar/4C_inpar_porofluidmultiphase.cpp
  src/inpar/4C_inpar_poromultiphase.cpp
  src/inpar/4C_inpar_poromultiphase_scatra.cpp
  src/inpar/4C_inpar_poroscatra.cpp
  src/inpar/4C_inpar_problemtype.cpp
  src/inpar/4C_inpar_rebalance.cpp
  src/inpar/4C_inpar_s2i.cpp
  src/inpar/4C_inpar_scatra.cpp
  src/inpar/4C_inpar_solver.cpp
  src/inpar/4C_inpar_solver_nonlin.cpp
  src/inpar/4C_inpar_ssi.cpp
  src/inpar/4C_inpar_ssti.cpp
  src/inpar/4C_inpar_sti.cpp
  src/inpar/4C_inpar_structure.cpp
  src/inpar/4C_inpar_tsi.cpp
  src/inpar/4C_inpar_validparameters.cpp
  src/inpar/4C_inpar_xfem.cpp
  src/lubrication/src/4C_lubrication_input.cpp
  src/thermo/src/utils/4C_thermo_input.cpp
Labels: team: input

#505 Remove BACI symbolic link
  apps/global_full/CMakeLists.txt
Labels: breaking change

#498 [epetra] Apply clang-tidy in graph wrapper
  src/contact/4C_contact_interface.cpp
  src/core/binstrategy/4C_binstrategy.cpp
  src/core/fem/src/condition/4C_fem_condition_periodic.cpp
  src/core/fem/src/discretization/4C_fem_discretization_partition.cpp
  src/core/io/src/4C_io_gridgenerator.cpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/linalg/src/sparse/4C_linalg_graph.cpp
  src/core/linalg/src/sparse/4C_linalg_graph.hpp
  src/core/linalg/src/sparse/4C_linalg_sparsematrix.cpp
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_manipulation.cpp
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
  src/core/linalg/tests/4C_linalg_utils_sparse_algebra_manipulation_test.np2.cpp
  src/core/rebalance/src/4C_rebalance_graph_based.cpp
  src/fsi/src/partitioned/4C_fsi_partitioned.cpp
Labels: taskforce: tpetra, type: clean code

#471 Implement pressure-velocity based solid poro element with primary porosity (solid-poro-p1)
  src/core/fem/src/general/element/4C_fem_general_element_definition.cpp
  src/global_legacy_module/4C_global_legacy_module.cpp
  src/poroelast/4C_poroelast_utils.cpp
  src/poroelast/4C_poroelast_utils_clonestrategy.cpp
  src/poroelast_scatra/4C_poroelast_scatra_utils.cpp
  src/poroelast_scatra/4C_poroelast_scatra_utils_clonestrategy.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib_p1.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_velocity_based.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_velocity_based.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_factory.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_factory.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_evaluate.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_p1.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_p1.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_p1_evaluate.cpp
  tests/input_files/poro_3D_hex8_p1.dat
Labels: taskforce: solid elements

#495 Assume yaml filename for --to-yaml if not given
  apps/global_full/4C_global_full_main.cpp
  src/core/io/src/4C_io_input_file.cpp
Labels: team: input

#515 Move beaminteraction potential input to physics
  src/beamcontact/4C_beamcontact_beam3contact_manager.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_input.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_input.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_beam_to_beam.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_beam_to_sphere.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_params.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_params.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_runtime_visualization_output_params.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_submodel_evaluator.cpp
  src/inpar/4C_inpar_beampotential.hpp
  src/inpar/4C_inpar_validconditions.cpp
  src/inpar/4C_inpar_validparameters.cpp
Labels: taskforce: modularization

#518 Remove old solid elements
  doc/readthedocs/elementtypes.rst
  src/contact/4C_contact_nitsche_integrator_fsi.cpp
  src/contact/4C_contact_nitsche_integrator_poro.cpp
  src/core/fem/src/general/element/4C_fem_general_element_definition.cpp
  src/global_legacy_module/4C_global_legacy_module.cpp
  src/mat/4C_mat_micromaterialgp_static.cpp
  src/poroelast_scatra/4C_poroelast_scatra_utils_clonestrategy.cpp
  src/so3/4C_so3_base.hpp
  src/so3/4C_so3_defines.hpp
  src/so3/4C_so3_hex27.cpp
  src/so3/4C_so3_hex27.hpp
  src/so3/4C_so3_hex27_evaluate.cpp
  src/so3/4C_so3_hex27_input.cpp
  src/so3/4C_so3_hex27_multiscale.cpp
  src/so3/4C_so3_hex27_service.cpp
  src/so3/4C_so3_hex8.cpp
  src/so3/4C_so3_hex8.hpp
  src/so3/4C_so3_hex8_determinant_analysis.cpp
  src/so3/4C_so3_hex8_determinant_analysis.hpp
  src/so3/4C_so3_hex8_eas.cpp
  src/so3/4C_so3_hex8_evaluate.cpp
  src/so3/4C_so3_hex8_input.cpp
  src/so3/4C_so3_hex8_multiscale.cpp
  src/so3/4C_so3_hex8_service.cpp
  src/so3/4C_so3_nurbs27.cpp
  src/so3/4C_so3_nurbs27.hpp
  src/so3/4C_so3_nurbs27_evaluate.cpp
  src/so3/4C_so3_nurbs27_input.cpp
  src/so3/4C_so3_prestress.cpp
  src/so3/4C_so3_prestress.hpp
  src/so3/4C_so3_prestress_service.hpp
  src/so3/4C_so3_surface_evaluate.cpp
  src/so3/4C_so3_tet10.cpp
  src/so3/4C_so3_tet10.hpp
  src/so3/4C_so3_tet10_evaluate.cpp
  src/so3/4C_so3_tet10_input.cpp
  src/so3/4C_so3_tet4.cpp
  src/so3/4C_so3_tet4.hpp
  src/so3/4C_so3_tet4_evaluate.cpp
  src/so3/4C_so3_tet4_input.cpp
  src/so3/4C_so3_tet4_multiscale.cpp
  src/so3/4C_so3_utils.cpp
  src/so3/4C_so3_utils.hpp
  src/so3/CMakeLists.txt
  src/stru_multi/4C_stru_multi_microstatic.cpp
  src/structure/4C_structure_timint_impl.cpp
  tests/input_files/old_solid_ele_contact3D_nitsche_hex8_skew_segm_new_struct.dat
  tests/input_files/old_solid_ele_contact3D_unbiased_self_hex8_nitsche_new_struct.dat
  tests/input_files/old_solid_ele_contact3D_unbiased_self_tet4_nitsche_ele_new_struct.dat
  tests/input_files/old_solid_ele_sohex8_beam3r_herm2line3_lie_group.dat
  tests/input_files/old_solid_ele_sohex8_easfull_cooks_nl_line_search_new_struc.dat
  tests/input_files/old_solid_ele_sohex8_easmild_cooks_nl.dat
  tests/list_of_tests.cmake
  unittests/so3/4C_so_hex8_determinant_analysis_test.cpp
  unittests/so3/4C_so_hex8_test.cpp
  unittests/so3/4C_so_tet4_test.cpp
Labels: breaking change

#519 Update pre-commit to version 4.1.0
  utilities/requirements.txt
Labels: type: bug report, team: infrastructure

#524 Remove helper to convert Yes/No to bool
  src/inpar/4C_inpar_boolifyparameters.cpp
  src/inpar/4C_inpar_boolifyparameters.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_aux.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_globaldata.cpp
  src/structure/4C_structure_timint_impl_nox.cpp
  tests/input_files/beam_flow_solver.xml
  tests/input_files/contact3D_nitsche_hex8_skew_segm_newtonLS_new_struc.xml
  tests/input_files/contact3D_nitsche_hex8_sym_coulomb_new_struc.xml
  tests/input_files/contact_two_beams_horizontal_new_struc.xml
  tests/input_files/fbi_part_struct_solver.xml
  tests/input_files/fsi_part_struct_solver.xml
  tests/input_files/fsi_part_struct_solver_potential_LJ.xml
  tests/input_files/plastic_necking_eas.xml
  tests/input_files/rough_contact_solver.xml
  tests/input_files/sohex8_eas_new_struc.xml
  tests/input_files/sohex8fbar_cooks_nl_new_struc.xml
  tests/input_files/soshw6_thin_nonlinear_pinched_hemisphere.xml
  tests/input_files/ssi_part_struct_solver.xml
  tests/input_files/tsi_meshtying_nurbs.xml
Labels: team: input

#510 Rework new selection to work with magic_enum
  src/core/io/src/4C_io_input_spec_builders.cpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  utilities/create_json_schema.py
  utilities/metadata_utils.py
Labels: team: input

#536 Fix bug in cmake testing functions for omp threads
  cmake/functions/four_c_testing_functions.cmake
  src/contact/4C_contact_strategy_factory.cpp
Labels: priority: high, team: testing

#534 Better errors for metadata and schema files
  apps/global_full/CMakeLists.txt
  utilities/metadata_utils.py
Labels: team: input

#531 BugFix: Add missing ConditionType enum strings
  src/core/legacy_enum_definitions/4C_legacy_enum_definitions_conditions.cpp
  src/ehl/4C_ehl_input.cpp
Labels: type: bug report

#540 Change porofluidmultiphase folder and files
  apps/global_full/4C_global_full_cal_control.cpp
  src/CMakeLists.txt
  src/adapter/4C_adapter_porofluidmultiphase_wrapper.cpp
  src/adapter/CMakeLists.txt
  src/inpar/4C_inpar_porofluid_pressure_based.cpp
  src/inpar/4C_inpar_porofluid_pressure_based.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_dyn.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_dyn.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_meshtying_strategy_artery.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_meshtying_strategy_artery.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_meshtying_strategy_base.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_meshtying_strategy_std.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_meshtying_strategy_std.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_resulttest.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_resulttest.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_ost.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_ost.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.hpp
  src/porofluid_pressure_based/CMakeLists.txt
  src/poromultiphase/4C_poromultiphase_base.cpp
  src/poromultiphase/4C_poromultiphase_utils.cpp
  src/poromultiphase/CMakeLists.txt
  src/poromultiphase_scatra/4C_poromultiphase_scatra_artery_coupling_linebased.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_artery_coupling_nonconforming.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_base.hpp
  src/poromultiphase_scatra/CMakeLists.txt
Labels: priority: low, type: clean code, team: poro

#542 Add additional inputs to gitignore
  .gitignore
Labels: priority: low, type: clean code

#543 Change porofluidmultiphase_ele
  src/CMakeLists.txt
  src/global_legacy_module/4C_global_legacy_module.cpp
  src/global_legacy_module/CMakeLists.txt
  src/mat/4C_mat_fluidporo_multiphase.cpp
  src/mat/CMakeLists.txt
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_ost.cpp
  src/porofluid_pressure_based/CMakeLists.txt
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_action.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_calc.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_calc.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_evaluate.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_factory.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_boundary_factory.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_calc.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_calc.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_calc_utils.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_calc_utils.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_evaluate.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_evaluator.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_evaluator.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_factory.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_factory.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_interface.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_parameter.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_parameter.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_phasemanager.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_phasemanager.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_variablemanager.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_variablemanager.hpp
  src/porofluid_pressure_based_ele/CMakeLists.txt
  src/poromultiphase/4C_poromultiphase_utils.cpp
  src/poromultiphase/4C_poromultiphase_utils_clonestrategy.cpp
  src/poromultiphase/CMakeLists.txt
  src/poromultiphase_scatra/4C_poromultiphase_scatra_artery_coupling_nonconforming.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_artery_coupling_pair.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_artery_coupling_pair.hpp
  src/poromultiphase_scatra/CMakeLists.txt
  src/scatra_ele/4C_scatra_ele_calc_multiporo_reac.hpp
  src/scatra_ele/CMakeLists.txt
Labels: priority: low, type: clean code, team: poro

#511 Membranes can now be written to output using vtk-based output
  apps/post_monitor/4C_post_monitor.cpp
  apps/post_monitor/4C_post_monitor.hpp
  apps/post_processor/4C_post_processor.cpp
  apps/post_processor/4C_post_processor_single_field_writers.cpp
  apps/post_processor/4C_post_processor_single_field_writers.hpp
  apps/post_processor/4C_post_processor_structure_stress.cpp
  src/inpar/4C_inpar_IO_runtime_vtk_output_structure.cpp
  src/inpar/4C_inpar_io.cpp
  src/inpar/4C_inpar_structure.hpp
  src/membrane/4C_membrane_evaluate.cpp
  src/post/4C_post_common.cpp
  src/post/4C_post_common.hpp
  src/structure_new/src/4C_structure_new_timint_base.cpp
  src/structure_new/src/4C_structure_new_timint_base.hpp
  src/structure_new/src/4C_structure_new_timint_basedataio.cpp
  src/structure_new/src/4C_structure_new_timint_basedataio.hpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.hpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.hpp
  src/structure_new/src/output/4C_structure_new_discretization_runtime_output_params.cpp
  src/structure_new/src/output/4C_structure_new_discretization_runtime_output_params.hpp
  tests/input_files/membrane_patch_new_struct.dat
  tests/input_files/ref/membrane_patch_new_struct/vtk-files/structure-00006-0.vtu
  tests/input_files/ref/membrane_patch_new_struct/vtk-files/structure-00006-1.vtu
  tests/input_files/ref/membrane_patch_new_struct/vtk-files/structure-00006.pvtu
Labels: taskforce: output, team: output

#547 Remove string_to_integral_parameter helper
  src/ale/4C_ale_input.cpp
  src/beamcontact/4C_beamcontact_input.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_input.cpp
  src/browniandyn/4C_browniandyn_input.cpp
  src/contact/4C_contact_input.cpp
  src/core/utils/src/parameters/4C_utils_parameter_list.cpp
  src/core/utils/src/parameters/4C_utils_parameter_list.hpp
  src/cut/4C_cut_input.cpp
  src/cut/4C_cut_intersection.hpp
  src/ehl/4C_ehl_input.cpp
  src/fbi/4C_fbi_input.cpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/fluid/4C_fluid_timint_hdg_weak_comp.cpp
  src/fluid_xfluid/4C_fluid_xfluid.cpp
  src/fluid_xfluid/4C_fluid_xfluid_fluid.cpp
  src/inpar/4C_inpar_IO_monitor_structure_dbc.cpp
  src/inpar/4C_inpar_IO_runtime_output.cpp
  src/inpar/4C_inpar_IO_runtime_vtk_output_structure.cpp
  src/inpar/4C_inpar_beam_to_solid.cpp
  src/inpar/4C_inpar_beaminteraction.cpp
  src/inpar/4C_inpar_binningstrategy.cpp
  src/inpar/4C_inpar_bio.cpp
  src/inpar/4C_inpar_cardiovascular0d.cpp
  src/inpar/4C_inpar_constraint_framework.cpp
  src/inpar/4C_inpar_elch.cpp
  src/inpar/4C_inpar_fluid.cpp
  src/inpar/4C_inpar_fluid.hpp
  src/inpar/4C_inpar_fpsi.cpp
  src/inpar/4C_inpar_fs3i.cpp
  src/inpar/4C_inpar_fsi.cpp
  src/inpar/4C_inpar_geometry_pair.cpp
  src/inpar/4C_inpar_io.cpp
  src/inpar/4C_inpar_levelset.cpp
  src/inpar/4C_inpar_mortar.cpp
  src/inpar/4C_inpar_mpc_rve.cpp
  src/inpar/4C_inpar_particle.cpp
  src/inpar/4C_inpar_pasi.cpp
  src/inpar/4C_inpar_plasticity.cpp
  src/inpar/4C_inpar_poroelast.cpp
  src/inpar/4C_inpar_porofluid_pressure_based.cpp
  src/inpar/4C_inpar_poromultiphase.cpp
  src/inpar/4C_inpar_poromultiphase_scatra.cpp
  src/inpar/4C_inpar_poroscatra.cpp
  src/inpar/4C_inpar_problemtype.cpp
  src/inpar/4C_inpar_rebalance.cpp
  src/inpar/4C_inpar_s2i.cpp
  src/inpar/4C_inpar_scatra.cpp
  src/inpar/4C_inpar_searchtree.cpp
  src/inpar/4C_inpar_solver.cpp
  src/inpar/4C_inpar_solver_nonlin.cpp
  src/inpar/4C_inpar_ssi.cpp
  src/inpar/4C_inpar_ssti.cpp
  src/inpar/4C_inpar_sti.cpp
  src/inpar/4C_inpar_structure.cpp
  src/inpar/4C_inpar_tsi.cpp
  src/inpar/4C_inpar_volmortar.cpp
  src/inpar/4C_inpar_wear.cpp
  src/inpar/4C_inpar_xfem.cpp
  src/lubrication/src/4C_lubrication_input.cpp
  src/thermo/src/utils/4C_thermo_input.cpp
Labels: team: input

#549 Rename porofluidmultiphase
  apps/global_full/4C_global_full_cal_control.cpp
  src/CMakeLists.txt
  src/adapter/4C_adapter_porofluid_pressure_based.hpp
  src/adapter/4C_adapter_porofluid_pressure_based_wrapper.cpp
  src/adapter/4C_adapter_porofluid_pressure_based_wrapper.hpp
  src/inpar/4C_inpar_porofluid_pressure_based_elast.cpp
  src/inpar/4C_inpar_porofluid_pressure_based_elast.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_adapter.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_base.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_base.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_dyn.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_dyn.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic_twoway.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic_twoway.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_partitioned.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_partitioned.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_partitioned_twoway.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_partitioned_twoway.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_utils.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_utils.hpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_utils_clonestrategy.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_utils_clonestrategy.hpp
  src/porofluid_pressure_based_elast/CMakeLists.txt
  src/poromultiphase_scatra/4C_poromultiphase_scatra_base.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_base.hpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_monolithic_twoway.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_partitioned_twoway.cpp
  src/poromultiphase_scatra/4C_poromultiphase_scatra_utils.cpp
  src/poromultiphase_scatra/CMakeLists.txt
Labels: priority: low, type: clean code, team: poro

#551 Emit knowledge about elements to metadata
  src/core/fem/src/general/element/4C_fem_general_element_definition.hpp
  src/core/io/src/4C_io_input_file.cpp
  src/core/io/src/4C_io_input_file.hpp
  src/global_data/4C_global_data_read.cpp
Labels: team: input

#557 Create LinAlg::View for our wrappers
  src/contact/4C_contact_lagrange_strategy_wear.cpp
  src/core/fem/tests/utils/4C_fem_general_element_dof_matrix_test.cpp
  src/core/linalg/src/sparse/4C_linalg_blocksparsematrix.cpp
  src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_projected_precond.cpp
  src/core/linalg/src/sparse/4C_linalg_vector.hpp
  src/core/linalg/src/sparse/4C_linalg_view.hpp
  src/core/linalg/tests/4C_linalg_vector_test.np2.cpp
  src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_preconditioner.cpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/ehl/4C_ehl_base.cpp
  src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_group.cpp
  src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_group.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_singlestep_group.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_ptc.cpp
  src/structure/4C_structure_timint_noxlinsys.cpp
  src/structure_new/src/implicit/4C_structure_new_impl_generic.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_contact.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.cpp
  src/structure_new/src/utils/4C_structure_new_dbc.cpp
Labels: taskforce: tpetra

#561 Add dummy job to set up docker image with deal.II
  .github/workflows/docker_dealii.yml
Labels: team: infrastructure

#553 Remove static functions from structure headers
  src/ale/4C_ale_ale3_evaluate.cpp
  src/beam3/4C_beam3_euler_bernoulli_input.cpp
  src/beam3/4C_beam3_kirchhoff_input.cpp
  src/beam3/4C_beam3_reissner_input.cpp
  src/contact/4C_contact_nitsche_integrator_ssi_elch.cpp
  src/fluid_ele/4C_fluid_ele_calc_hdg.cpp
  src/fluid_ele/4C_fluid_ele_calc_poro.cpp
  src/fsi/src/4C_fsi_dyn.cpp
  src/fsi/src/partitioned/4C_fsi_partitioned.cpp
  src/global_data/4C_global_data_read.cpp
  src/inpar/4C_inpar_structure.cpp
  src/inpar/4C_inpar_structure.hpp
  src/mat/4C_mat_so3_material.cpp
  src/mat/4C_mat_so3_material.hpp
  src/mixture/4C_mixture_constituent_elasthyperbase.cpp
  src/mixture/4C_mixture_constituent_solidmaterial.cpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/poroelast/4C_poroelast_monolithicmeshtying.cpp
  src/poroelast/4C_poroelast_utils.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic_twoway.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_phasemanager.cpp
  src/rigidsphere/4C_rigidsphere_evaluate.cpp
  src/scatra_ele/4C_scatra_ele.cpp
  src/scatra_ele/4C_scatra_ele_boundary_calc.cpp
  src/scatra_ele/4C_scatra_ele_calc_advanced_reaction.cpp
  src/scatra_ele/4C_scatra_ele_calc_poro_reac.cpp
  src/scatra_ele/4C_scatra_ele_calc_poro_reac_ECM.cpp
  src/shell7p/4C_shell7p_utils.cpp
  src/solid_3D_ele/4C_solid_3D_ele.cpp
  src/solid_3D_ele/4C_solid_3D_ele_factory.cpp
  src/solid_3D_ele/4C_solid_3D_ele_factory_lib.hpp
  src/solid_3D_ele/4C_solid_3D_ele_properties.cpp
  src/solid_3D_ele/4C_solid_3D_ele_properties.hpp
  src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele.cpp
  src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_factory.cpp
  src/stru_multi/4C_stru_multi_microstatic_npsupport.cpp
  src/structure/4C_structure_timada.cpp
  src/structure/4C_structure_timada.hpp
  src/structure/4C_structure_timint.cpp
  src/structure/4C_structure_timint_impl_nox.cpp
  src/structure_new/src/4C_structure_new_integrator.cpp
  src/structure_new/src/4C_structure_new_timint_base.cpp
  src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp
  src/structure_new/src/4C_structure_new_timint_basedataglobalstate.hpp
  src/structure_new/src/linear_solver/4C_structure_new_solver_factory.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_manager.cpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc.cpp
  src/structure_new/src/utils/4C_structure_new_resulttest.cpp
  src/structure_new/src/utils/4C_structure_new_utils.cpp
  src/thermo/src/element/4C_thermo_ele_impl.cpp
  src/tsi/4C_tsi_dyn.cpp
  src/w1/4C_w1_eas.cpp
  src/w1/4C_w1_mat.cpp
Labels: team: input

#560 Remove gitlab remnants
  tests/testconfig/.gitlab-ci.yml
  tests/testconfig/README.md
  utilities/four_c_utils/src/four_c_utils/check_workflow_dependencies_hash.py
Labels: team: infrastructure

#565 Remove a do-nothing pre-evaluate
  src/fluid_ele/4C_fluid_ele_calc_poro.cpp
  src/fluid_ele/4C_fluid_ele_calc_poro.hpp
  src/fluid_ele/4C_fluid_ele_calc_poro_p1.cpp
Labels: type: clean code

#559 Remove function domain_map_not_epetra
  src/constraint/4C_constraint_solver.cpp
  src/constraint_framework/4C_constraint_framework_submodelevaluator_base.cpp
  src/contact/4C_contact_lagrange_strategy.cpp
  src/contact/4C_contact_lagrange_strategy_poro.cpp
  src/contact/4C_contact_meshtying_lagrange_strategy.cpp
  src/contact/4C_contact_nox_nln_contact_linearsystem.cpp
  src/core/linalg/src/sparse/4C_linalg_blocksparsematrix.hpp
  src/core/linalg/src/sparse/4C_linalg_sparsematrixbase.hpp
  src/core/linalg/src/sparse/4C_linalg_sparseoperator.hpp
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_manipulation.cpp
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
  src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_objects.cpp
  src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_vcycle.cpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/coupling/src/adapter/4C_coupling_adapter_converter.cpp
  src/coupling/src/adapter/4C_coupling_adapter_volmortar.cpp
  src/fpsi/4C_fpsi_monolithic_plain.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_monolithicfluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_mortarmonolithic_fluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_mortarmonolithic_structuresplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_slidingmonolithic_fluidsplit.cpp
  src/fsi/src/monolithic/model_evaluator/4C_fsi_slidingmonolithic_structuresplit.cpp
  src/fsi_xfem/4C_fsi_xfem_coupling_comm_manager.cpp
  src/mortar/4C_mortar_utils.cpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp
  src/ssi/4C_ssi_monolithic_meshtying_strategy.cpp
  src/ssti/4C_ssti_monolithic_assemble_strategy.cpp
  src/sti/4C_sti_monolithic.cpp
  src/structure/4C_structure_timint.cpp
  src/structure/4C_structure_timint_impl.cpp
  src/structure_new/src/4C_structure_new_timint_base.cpp
Labels: status: ready, type: clean code

#572 Only communicate small sections when reading yaml
  src/core/io/src/4C_io_input_file.cpp
Labels: team: input

#563 Simplify potential params
  src/beamcontact/4C_beamcontact_beam3contact_manager.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_input.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_base.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_base.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_beam_to_beam.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_pair_beam_to_sphere.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_params.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_params.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_runtime_visualization_output_params.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_runtime_visualization_output_params.hpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_submodel_evaluator.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_submodel_evaluator.hpp
  tests/input_files/beam3eb_genalpha_BTB_contact_elstat_attraction_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_backweuler_browndyn_repLJ_singlelengthspec_smallsepapprox_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_backweuler_browndyn_vanderWaals_doublelengthspec_smallsepapprox_regularization_constextpol_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_backweuler_browndyn_vanderWaals_doublelengthspec_smallsepapprox_regularization_linextpol_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_backweuler_browndyn_vanderWaals_doublelengthspec_smallsepapprox_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_backweuler_browndyn_vanderWaals_singlelengthspec_smallsepapprox_twocrossedbeams.dat
  tests/input_files/beam3r_herm2line3_static_BTBpotential_repulsiveLennardJones_beamrotatingoverarc.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_regularization_linextpol_twocrossedbeams_pulloff.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_simple_regularization_linextpol_twocrossedbeams_pulloff.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_simple_regularization_linextpol_twocrossedbeams_pulloff_FAD.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_simple_regularization_linextpol_twocrossedbeams_pulloff_highereleGIDisslave.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_simple_twocrossedbeams_pulloff.dat
  tests/input_files/beam3r_herm2line3_static_LJ_singlelengthspec_smallsepapprox_simple_twocrossedbeams_pulloff_FAD.dat
  tests/input_files/beam3r_herm2line3_static_vdW_singlelengthsspec_smallsepapprox_simple_end_point_potential_reduction_strategy.dat
Labels: breaking change

#578 Remove an expensive include from LinAlg::Map
  src/core/linalg/src/sparse/4C_linalg_map.hpp
Labels: type: clean code

#581 Use ValueParser for parsing of nodes
  src/core/io/src/4C_io_nodereader.cpp
  src/core/io/src/4C_io_value_parser.cpp
  tests/input_files/red_airway_5000_airway_acinus_collapsible.dat
  tests/input_files/reduced_lung_3_aw_2_tu.dat
  tests/input_files/reduced_lung_aw_bifurcation_flow.dat
  tests/input_files/reduced_lung_aw_bifurcation_no_flow.dat
  tests/input_files/reduced_lung_serial_airways_flow.dat
  tests/input_files/reduced_lung_serial_airways_no_flow.dat
  tests/input_files/reduced_lung_terminal_unit.dat
Labels: type: clean code, team: input

#587 Relax tolerance for a xffsi test
  tests/input_files/xffsi_monolithic_ss_1D_interpAle_inflow_fixedstr.dat
Labels: priority: high

#585 Enhance build time analysis with ninjatracing
  .github/workflows/nightly_tests.yml
Labels: team: infrastructure

#566 Remove ElementType::pre_evaluate
  src/contact/4C_contact_friction_node.hpp
  src/contact/4C_contact_line_coupling.hpp
  src/core/comm/src/4C_comm_parobjectfactory.cpp
  src/core/comm/src/4C_comm_parobjectfactory.hpp
  src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp
  src/core/fem/src/dofset/4C_fem_dofset_definedmapping_wrapper.hpp
  src/core/fem/src/dofset/4C_fem_dofset_pbc.hpp
  src/core/fem/src/general/element/4C_fem_general_elementtype.hpp
  src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization_knotvector.cpp
  src/cut/4C_cut_cutwizard.hpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/fluid/4C_fluid_timint_bdf2.cpp
  src/fluid/4C_fluid_timint_genalpha.cpp
  src/fluid/4C_fluid_timint_loma.cpp
  src/fluid/4C_fluid_timint_ost.cpp
  src/fluid/4C_fluid_timint_poro.cpp
  src/fluid/4C_fluid_timint_stat.cpp
  src/fluid/4C_fluid_timint_stat_hdg.cpp
  src/fluid_ele/4C_fluid_ele.hpp
  src/fluid_ele/4C_fluid_ele_action.hpp
  src/fluid_ele/4C_fluid_ele_calc_intfaces_stab.hpp
  src/fluid_ele/4C_fluid_ele_evaluate.cpp
  src/fluid_ele/4C_fluid_ele_hdg.cpp
  src/fluid_ele/4C_fluid_ele_hdg_weak_comp.cpp
  src/fluid_ele/4C_fluid_ele_poro.hpp
  src/fluid_ele/4C_fluid_ele_poro_evaluate.cpp
  src/fluid_xfluid/4C_fluid_xfluid.cpp
  src/levelset/4C_levelset_algorithm_reinit.cpp
  src/lubrication/src/4C_lubrication_ele.hpp
  src/lubrication/src/4C_lubrication_ele_action.hpp
  src/lubrication/src/4C_lubrication_ele_evaluate.cpp
  src/lubrication/src/4C_lubrication_timint_implicit.cpp
  src/lubrication/src/4C_lubrication_timint_stat.cpp
  src/mortar/4C_mortar_node.hpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_ost.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_action.hpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_evaluate.cpp
  src/scatra/4C_scatra_timint_bdf2.cpp
  src/scatra/4C_scatra_timint_elch.cpp
  src/scatra/4C_scatra_timint_genalpha.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/scatra/4C_scatra_timint_implicit_service.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
  src/scatra/4C_scatra_timint_ost.cpp
  src/scatra/4C_scatra_timint_stat.cpp
  src/scatra/4C_scatra_timint_stat_hdg.cpp
  src/scatra_ele/4C_scatra_ele.hpp
  src/scatra_ele/4C_scatra_ele_action.hpp
  src/scatra_ele/4C_scatra_ele_evaluate.cpp
  src/scatra_ele/4C_scatra_ele_hdg.cpp
  src/ssi/4C_ssi_manifold_utils.cpp
Labels: type: clean code

#580 Enhance legacy section metadata with more info
  src/global_data/4C_global_data_read.cpp
  src/particle_engine/4C_particle_engine_enums.cpp
  src/particle_engine/4C_particle_engine_enums.hpp
  src/particle_engine/4C_particle_engine_particlereader.cpp
  src/particle_engine/4C_particle_engine_particlereader.hpp
Labels: type: enhancement, team: input
