Repository 4C-multiphysics/4C, pull requests merged in 2025-08, with the labels that each got.

#1034 Fix bugs uncovered by _GLIBCXX_ASSERTIONS in minimal tests
  src/core/comm/src/4C_comm_exporter.cpp
  src/core/fem/src/discretization/4C_fem_discretization_conditions.cpp
  src/ssi/4C_ssi_monolithic.cpp
  src/ssi/4C_ssi_monolithic_assemble_strategy.cpp
  src/ssi/4C_ssi_monolithic_assemble_strategy.hpp
  src/xfem/4C_xfem_condition_manager.cpp
Labels: type: bug report

#1030 InputSpec: allow validation of vectors of optional types
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_input_spec_validators.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  src/inpar/4C_inpar_ssi.cpp
  tests/input_files/ssi_mono_3D_6hex8_elch_s2i_butlervolmer_grain_boundary.4C.yaml
  tests/input_files/ssi_mono_3D_hex8_elch_s2i_butlervolmer_grain_boundary_meshtying_BGS-AMG_5x5.4C.yaml
  tests/input_files/ssi_mono_3D_tet4_elch_s2i_butlervolmer_manifold_BGS-AMG_11x11.4C.yaml
  tests/input_files/ssi_mono_3D_tet4_elch_s2i_butlervolmer_manifold_BGS-AMG_3x3.4C.yaml
Labels: type: enhancement, team: input

#1048 Let dependabot look into subdirectories
  .github/dependabot.yml
Labels: team: infrastructure

#1033 Enable _GLIBCXX_ASSERTIONS in assert mode
  cmake/setup_global_options.cmake
  src/constraint/4C_constraint_penalty.cpp
  src/constraint/4C_constraint_penalty.hpp
  src/fluid_ele/4C_fluid_ele_calc_xfem.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem.hpp
  src/fluid_ele/4C_fluid_ele_evaluate.cpp
  src/fluid_ele/4C_fluid_ele_evaluate_utils.hpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
Labels: type: clean code, team: infrastructure

#1062 Remove some raw Epetra calls
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_mortar_manager.cpp
  src/beaminteraction/src/4C_beaminteraction_str_model_evaluator.cpp
  src/beaminteraction/src/4C_beaminteraction_str_model_evaluator_datastate.cpp
  src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_mortar_manager.cpp
  src/contact/4C_contact_lagrange_strategy.cpp
  src/contact/4C_contact_lagrange_strategy_wear.cpp
  src/contact/4C_contact_nitsche_strategy.cpp
  src/contact/4C_contact_nitsche_strategy_poro.cpp
  src/contact/4C_contact_nitsche_strategy_ssi.cpp
  src/contact/4C_contact_wear_interface.cpp
  src/core/linalg/src/sparse/4C_linalg_fevector.hpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/ehl/4C_ehl_base.cpp
  src/fbi/4C_fbi_adapter_constraintbridge_penalty.cpp
  src/fbi/4C_fbi_beam_to_fluid_mortar_manager.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
Labels: taskforce: tpetra

#1065 Schema validation for vectors
  utilities/create_json_schema.py
  utilities/metadata_utils.py
Labels: team: input

#1066 Generalize norms evaluation for NOX vectors and reduce the use of `get_ref_of_epetra_vector()`
  src/constraint/4C_constraint_lagpenconstraint_noxinterface.cpp
  src/contact/4C_contact_meshtying_noxinterface.cpp
  src/contact/4C_contact_noxinterface.cpp
  src/fs3i/4C_fs3i_biofilm_fsi.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_aux.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_aux.hpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.hpp
Labels: taskforce: tpetra

#1064 Reserve container space when parsing YAML
  src/core/io/src/4C_io_yaml.hpp
Labels: team: input

#1072 [cmake] Cleanup python dependency
  CMakeLists.txt
  apps/global_full/CMakeLists.txt
  cmake/configure/configure_Python.cmake
  cmake/functions/four_c_configure_dependency.cmake
  cmake/functions/four_c_testing_functions.cmake
  doc/documentation/CMakeLists.txt
  presets/docker/CMakePresets.json
  tests/list_of_tests.cmake
Labels: type: clean code, team: infrastructure

#1083 Fix error in linear solver factory for new structure
  src/structure_new/src/linear_solver/4C_structure_new_solver_factory.cpp
  src/structure_new/src/linear_solver/4C_structure_new_solver_factory.hpp
Labels: team: solvers

#1074 Allow documentation of enum values in input
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/src/4C_io_exodus.hpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  src/global_legacy_module/4C_global_legacy_module_validparameters.cpp
  utilities/create_json_schema.py
  utilities/metadata_utils.py
Labels: type: enhancement, team: input

#1105 Remove two empty cpp files
  src/geometry_pair/4C_geometry_pair.cpp
  src/geometry_pair/4C_geometry_pair_evaluation_data_base.cpp
Labels: type: clean code

#1106 Remove a few non-configurable defines
  src/ale/4C_ale_meshtying.cpp
  src/fluid/4C_fluid_meshtying.cpp
Labels: type: clean code

#1098 Replace `Epetra_LinearProblem` with a custom class
  src/contact/4C_contact_nox_nln_contact_linearsystem.cpp
  src/contact/4C_contact_nox_nln_contact_linearsystem.hpp
  src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.cpp
  src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_forward_decl.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearproblem.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_scaling.hpp
  src/structure/4C_structure_timint_noxlinsys.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp
  src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.hpp
Labels: taskforce: tpetra

#1113 Remove Epetra_BlockMap from constructors
  src/core/fem/src/general/utils/4C_fem_general_utils_superconvergent_patch_recovery.cpp
  src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp
  src/core/linalg/src/sparse/4C_linalg_fevector.cpp
  src/core/linalg/src/sparse/4C_linalg_fevector.hpp
  src/core/linalg/src/sparse/4C_linalg_graph.cpp
  src/core/linalg/src/sparse/4C_linalg_graph.hpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_linebased.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_nonconforming.cpp
  src/thermo/src/implicit/4C_thermo_timint_impl.cpp
Labels: taskforce: tpetra, type: clean code

#1101 Give InputSpec shallow copy behavior
  src/core/io/src/4C_io_input_file.cpp
  src/core/io/src/4C_io_input_spec.cpp
  src/core/io/src/4C_io_input_spec.hpp
  src/core/io/src/4C_io_input_spec_builders.cpp
Labels: team: input

#1129 Cmake: move internal dependencies to module root
  src/beaminteraction/CMakeLists.txt
  src/beaminteraction/src/CMakeLists.txt
  src/coupling/CMakeLists.txt
  src/coupling/src/adapter/CMakeLists.txt
  src/fsi/CMakeLists.txt
  src/fsi/src/CMakeLists.txt
  src/lubrication/CMakeLists.txt
  src/lubrication/src/CMakeLists.txt
  src/mixture/CMakeLists.txt
  src/mixture/src/CMakeLists.txt
  src/shell_kl_nurbs/CMakeLists.txt
  src/shell_kl_nurbs/src/CMakeLists.txt
  src/structure_new/CMakeLists.txt
  src/structure_new/src/CMakeLists.txt
  src/structure_new/src/explicit/CMakeLists.txt
  src/structure_new/src/implicit/CMakeLists.txt
  src/structure_new/src/linear_solver/CMakeLists.txt
  src/structure_new/src/model_evaluator/CMakeLists.txt
  src/structure_new/src/nonlinear_solver/CMakeLists.txt
  src/structure_new/src/output/CMakeLists.txt
  src/structure_new/src/predict/CMakeLists.txt
  src/structure_new/src/utils/CMakeLists.txt
  src/thermo/CMakeLists.txt
  src/thermo/src/CMakeLists.txt
Labels: type: clean code, team: infrastructure

#1136 Add pattern validator for input strings
  src/core/io/src/4C_io_input_spec_validators.cpp
  src/core/io/src/4C_io_input_spec_validators.hpp
  src/core/io/tests/4C_io_input_spec_validators_test.cpp
  src/inpar/4C_inpar_scatra.cpp
  utilities/create_json_schema.py
  utilities/metadata_utils.py
Labels: team: input

#1130 Enable teko for elch problems
  src/cardiovascular0d/4C_cardiovascular0d_manager.cpp
  src/constraint/4C_constraint_solver.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_linalg.hpp
  src/fpsi/4C_fpsi_monolithic.cpp
  src/fs3i/4C_fs3i_fps3i_partitioned.cpp
  src/fs3i/4C_fs3i_partitioned.cpp
  src/fsi/src/monolithic/4C_fsi_monolithic.cpp
  src/fsi_xfem/4C_fsi_xfem_monolithic.cpp
  src/loma/4C_loma_algorithm.cpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/scatra/4C_scatra_timint_elch.cpp
  src/scatra/4C_scatra_timint_elch.hpp
  src/scatra/4C_scatra_timint_elch_scl.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/scatra/4C_scatra_timint_implicit.hpp
  src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
  src/scatra/4C_scatra_timint_meshtying_strategy_std_elch.cpp
  src/ssi/4C_ssi_manifold_utils.cpp
  src/ssi/4C_ssi_monolithic.cpp
  src/ssi/4C_ssi_monolithic_evaluate_OffDiag.cpp
  src/ssi/4C_ssi_utils.cpp
  src/ssti/4C_ssti_monolithic.cpp
  src/ssti/4C_ssti_monolithic_evaluate_OffDiag.cpp
  src/ssti/4C_ssti_utils.cpp
  src/sti/4C_sti_monolithic.cpp
  src/sti/4C_sti_monolithic.hpp
  src/sti/4C_sti_monolithic_evaluate_OffDiag.cpp
  src/structure_new/src/linear_solver/4C_structure_new_solver_factory.cpp
  src/tsi/4C_tsi_monolithic.cpp
  tests/input_files/elch_3D_hex8_line2_scl_2dof_BGS_AMG_2x2.4C.yaml
  tests/input_files/elch_3D_hex8_line2_scl_2dof_BGS_AMG_2x2.xml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_AMG-BGS_3x3.4C.yaml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_AMG-BGS_3x3.xml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_BGS-AMG_3x3.4C.yaml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_BGS-AMG_3x3.xml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_mortar_standard_BGS-AMG_3x3.4C.yaml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_mortar_standard_BGS-AMG_3x3.xml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_mortar_standard_redist_BGS-AMG_3x3.4C.yaml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_plating_monolithic_reg_trig_BGS-AMG_4x4.4C.yaml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_plating_monolithic_reg_trig_BGS-AMG_4x4.xml
  tests/input_files/elch_3D_tet4_s2i_butlervolmer_plating_monolithic_reg_trig_BGS-AMG_4x4_scatra.xml
  tests/input_files/xml/block_preconditioner/electrochemistry_BGS-AMG_2x2.xml
  tests/input_files/xml/block_preconditioner/electrochemistry_BGS-AMG_3x3.xml
  tests/input_files/xml/block_preconditioner/electrochemistry_BGS-AMG_4x4.xml
  tests/input_files/xml/linear_solver/iterative_gmres_template_adaptive_tolerance.xml
  tests/input_files/xml/multigrid/elch_AMG-BGS_3x3.xml
Labels: taskforce: tpetra

#1135 CMake: document FOUR_C_CXX_ variables
  cmake/functions/four_c_process_global_option.cmake
  cmake/setup_global_options.cmake
Labels: team: infrastructure, breaking change

#1149 Let Graph return MPI_Comm instead of EpetraComm
  src/core/fem/src/condition/4C_fem_condition_periodic.cpp
  src/core/linalg/src/sparse/4C_linalg_graph.hpp
  src/core/rebalance/src/4C_rebalance_graph_based.cpp
Labels: taskforce: tpetra, type: clean code

#1157 Fix Epetra_Operator pointer in older versions
  src/core/linear_solver/src/method/4C_linear_solver_method_direct.cpp
Labels: priority: high, type: bug report, team: solvers

#1158 Fix flaky mat_druckerprager test
  tests/input_files/mat_druckerprager_RetToCone.4C.yaml
  tests/input_files/ref/mat_druckerprager_RetToCone/Framework-DP-vtk-files/structure-00019-0.vtu
  tests/input_files/ref/mat_druckerprager_RetToCone/Framework-DP-vtk-files/structure-00019-1.vtu
  tests/input_files/ref/mat_druckerprager_RetToCone/Framework-DP-vtk-files/structure-00019.pvtu
  tests/input_files/ref/mat_druckerprager_RetToCone/RetToCone-structure.pvd
Labels: priority: high

#1161 Minor cleanup in Knotvectors
  src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization_knotvector.cpp
  src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization_knotvector.hpp
  src/core/io/src/4C_io_input_file_utils.cpp
  src/core/io/src/4C_io_input_file_utils.hpp
  src/global_data/4C_global_data_read.cpp
  unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_geometry_functions_test.hpp
Labels: type: clean code, team: input

#1173 Remove some EpetraCrs matrix calls
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
Labels: taskforce: tpetra

#1172 Remove shared_ptr on Communicators
  apps/global_full/4C_global_full_io.cpp
  apps/global_full/4C_global_full_io.hpp
  apps/global_full/4C_global_full_main.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_visualization_output_writer_visualization.cpp
  src/core/comm/src/4C_comm_utils.cpp
  src/core/comm/src/4C_comm_utils.hpp
  src/core/comm/tests/4C_comm_utils_test.np3.cpp
  src/global_data/4C_global_data.cpp
  src/global_data/4C_global_data.hpp
  src/global_data/4C_global_data_read.cpp
  src/mat/4C_mat_aaaneohooke.cpp
  src/mat/4C_mat_constraintmixture.cpp
  src/mat/4C_mat_micromaterial_evaluate.cpp
  src/mat/4C_mat_scatra.cpp
  src/particle_algorithm/4C_particle_algorithm_sim.cpp
  src/stru_multi/4C_stru_multi_microstatic.cpp
  src/stru_multi/4C_stru_multi_microstatic_npsupport.cpp
  src/structure_new/src/4C_structure_new_timint_base.cpp
  src/structure_new/src/4C_structure_new_timint_basedatasdyn.cpp
  tests/benchmark_tests/solid_3D_ele/4C_solid_3D_ele_evaluation_benchmark.cpp
  unittests/mat/4C_electrode_test.cpp
Labels: type: clean code

#1176 Remove NOX from old structure time int
  src/inpar/4C_inpar_structure.cpp
  src/inpar/4C_inpar_structure.hpp
  src/structure/4C_structure_timint_impl.cpp
  src/structure/4C_structure_timint_impl.hpp
  src/structure/4C_structure_timint_impl_nox.cpp
  src/structure/4C_structure_timint_noxgroup.cpp
  src/structure/4C_structure_timint_noxgroup.hpp
  src/structure/4C_structure_timint_noxlinsys.cpp
  src/structure/4C_structure_timint_noxlinsys.hpp
  tests/input_files/strufem_hex8_cantilever.4C.yaml
  tests/list_of_tests.cmake
Labels: taskforce: tpetra, type: clean code, team: structure

#1187 Move SSI, SSTI and STI input to physics
  src/adapter/4C_adapter_scatra_base_algorithm.cpp
  src/adapter/CMakeLists.txt
  src/contact/src/4C_contact_strategy_factory.cpp
  src/global_legacy_module/4C_global_legacy_module_validconditions.cpp
  src/global_legacy_module/4C_global_legacy_module_validparameters.cpp
  src/inpar/4C_inpar_ssi.hpp
  src/inpar/4C_inpar_ssti.hpp
  src/inpar/4C_inpar_sti.hpp
  src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.cpp
  src/ssi/4C_ssi_base.cpp
  src/ssi/4C_ssi_base.hpp
  src/ssi/4C_ssi_clonestrategy.cpp
  src/ssi/4C_ssi_dyn.cpp
  src/ssi/4C_ssi_input.cpp
  src/ssi/4C_ssi_input.hpp
  src/ssi/4C_ssi_manifold_utils.cpp
  src/ssi/4C_ssi_monolithic.cpp
  src/ssi/4C_ssi_monolithic.hpp
  src/ssi/4C_ssi_partitioned_2wc.hpp
  src/ssti/4C_ssti_algorithm.cpp
  src/ssti/4C_ssti_algorithm.hpp
  src/ssti/4C_ssti_dyn.cpp
  src/ssti/4C_ssti_input.cpp
  src/ssti/4C_ssti_input.hpp
  src/sti/4C_sti_dyn.cpp
  src/sti/4C_sti_input.cpp
  src/sti/4C_sti_input.hpp
  src/sti/4C_sti_monolithic.cpp
  src/sti/4C_sti_partitioned.cpp
  src/sti/4C_sti_partitioned.hpp
  unittests/mat/4C_multiplicative_split_defgrad_elasthyper_test.cpp
Labels: taskforce: modularization
