Repository 4C-multiphysics/4C, pull requests merged in 2025-09, with the labels that each got.

#1203 Remove untested code from cut framework
  src/cut/4C_cut_elementhandle.cpp
  src/cut/4C_cut_facet_integration.cpp
  src/cut/4C_cut_facet_integration.hpp
  src/cut/4C_cut_line_integration.cpp
  src/cut/4C_cut_line_integration.hpp
  src/cut/4C_cut_quadrature_compression.cpp
  src/cut/4C_cut_quadrature_compression.hpp
  src/cut/4C_cut_volume_integration.cpp
  src/cut/4C_cut_volume_integration.hpp
  src/cut/4C_cut_volumecell.cpp
Labels: type: clean code

#1217 Fix UB in direct linear solver
  src/core/linear_solver/src/method/4C_linear_solver_method_direct.cpp
Labels: priority: high

#1209 Implement a wrapper around Teuchos::SerialDenseMatrix and hide Trilinos access in user code
  src/ale/4C_ale_ale2_evaluate.cpp
  src/art_net/4C_art_net_art_junction.cpp
  src/contact/src/4C_contact_rough_node.cpp
  src/contact_constitutivelaw/src/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.cpp
  src/core/fem/src/general/utils/4C_fem_general_utils_gauss_point_extrapolation.cpp
  src/core/fem/src/general/utils/4C_fem_general_utils_polynomial.cpp
  src/core/fem/src/general/utils/4C_fem_general_utils_polynomial.hpp
  src/core/linalg/src/dense/4C_linalg_serialdensematrix.cpp
  src/core/linalg/src/dense/4C_linalg_serialdensematrix.hpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_eigen.cpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_eigen.hpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_multiply.hpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_svd.cpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_svd.hpp
  src/core/linalg/src/dense/4C_linalg_utils_tensor_interpolation.cpp
  src/core/linalg/src/sparse/4C_linalg_krylov_projector.cpp
  src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
  src/core/utils/src/numerics/4C_utils_cubic_spline_interpolation.cpp
  src/fluid_ele/4C_fluid_ele_boundary_parent_calc.cpp
  src/fluid_ele/4C_fluid_ele_boundary_parent_calc.hpp
  src/fluid_ele/4C_fluid_ele_calc_hdg.cpp
  src/fluid_ele/4C_fluid_ele_calc_hdg_weak_comp.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem.hpp
  src/fluid_ele/4C_fluid_ele_calc_xfem_coupling.cpp
  src/fluid_ele/4C_fluid_ele_calc_xfem_coupling.hpp
  src/fluid_ele/4C_fluid_ele_calc_xfem_coupling_impl.hpp
  src/fluid_ele/4C_fluid_ele_calc_xfem_coupling_impl_nitsche.cpp
  src/fluid_ele/4C_fluid_ele_calc_xwall.cpp
  src/fluid_ele/4C_fluid_ele_intfaces_calc.cpp
  src/mat/4C_mat_fluidporo_multiphase.cpp
  src/mat/4C_mat_growthremodel_elasthyper.cpp
  src/mortar/src/4C_mortar_element_shapefct.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele_phasemanager.cpp
  src/scatra_ele/4C_scatra_ele_calc_cardiac_monodomain_hdg.cpp
  src/scatra_ele/4C_scatra_ele_calc_hdg.cpp
  src/scatra_ele/4C_scatra_ele_calc_service_elch_diffcond_multiscale.cpp
  src/shell7p/4C_shell7p_ele_calc_eas.cpp
  src/shell7p/4C_shell7p_ele_calc_eas_utils.hpp
  src/shell7p/4C_shell7p_ele_calc_lib.hpp
  src/shell7p/4C_shell7p_line.hpp
  src/shell7p/4C_shell7p_line_evaluate.cpp
  src/shell7p/4C_shell7p_utils.cpp
  src/shell7p/4C_shell7p_utils.hpp
  src/solid_3D_ele/4C_solid_3D_ele_evaluate.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
  src/w1/4C_w1_eas.cpp
  src/w1/4C_w1_evaluate.cpp
  src/w1/4C_w1_line_evaluate.cpp
  src/w1/4C_w1_poro_evaluate.cpp
  src/xfem/4C_xfem_coupling_mesh.cpp
  src/xfem/4C_xfem_utils.cpp
  src/xfem/4C_xfem_utils.hpp
  unittests/common/unittest_utils/4C_unittest_utils_assertions_test.hpp
Labels: type: enhancement

#1226 [Beaminteraction] Add Euler-Bernoulli testcases with Lagrange Multipliers
  tests/input_files/beam3eb_static_beam_to_solid_volume_meshtying_mortar_lagrange_regularized_line3.4C.yaml
  tests/input_files/beam3eb_static_beam_to_solid_volume_meshtying_mortar_lagrange_saddlepoint_line3.4C.yaml
  tests/input_files/beam3eb_static_beam_to_solid_volume_meshtying_mortar_penalty_line3.4C.yaml
  tests/list_of_tests.cmake
Labels: type: enhancement

#1231 Add FlatVectorVector<T> data structure
  src/core/utils/src/stl_extension/4C_utils_flat_vector_vector.hpp
  src/core/utils/tests/stl_extension/4C_utils_flat_vector_vector_test.cpp
Labels: type: enhancement

#1234 Enhance DiscretizationIterator functionality
  src/core/fem/src/discretization/4C_fem_discretization_iterator.hpp
  src/core/fem/tests/discretization/4C_fem_discretization_iterator_test.cpp
Labels: type: enhancement, team: discretization

#1237 Add ElementRef to Discretization
  src/core/fem/src/condition/4C_fem_condition_selector.cpp
  src/core/fem/src/condition/4C_fem_condition_utils.cpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_fillcomplete.cpp
  src/core/fem/src/general/node/4C_fem_general_node.hpp
  src/core/fem/src/geometry/4C_fem_geometry_update_reference_config.cpp
  src/core/io/src/4C_io_discretization_visualization_writer_nodes.cpp
  src/reduced_lung/4C_reduced_lung_main.cpp
  src/shell7p/4C_shell7p_utils.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_meshtying.cpp
  src/thermo/src/implicit/4C_thermo_timint_impl.cpp
Labels: type: enhancement, team: discretization

#1247 Use ElementRef in discretization loops
  src/contact/src/4C_contact_interface.cpp
  src/core/binstrategy/4C_binstrategy.cpp
  src/core/binstrategy/4C_binstrategy.hpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
  src/core/fem/src/discretization/4C_fem_discretization_fillcomplete.cpp
  src/core/fem/src/general/utils/4C_fem_general_l2_projection.cpp
  src/core/io/src/4C_io.cpp
  src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp
  src/core/rebalance/src/4C_rebalance_graph_based.cpp
  src/mat/4C_mat_micromaterialgp_static.cpp
  src/mortar/src/4C_mortar_interface.cpp
  src/poroelast/4C_poroelast_utils.cpp
  src/poroelast_scatra/4C_poroelast_scatra_utils.cpp
  src/reduced_lung/src/4C_reduced_lung_main.cpp
  src/shell7p/4C_shell7p_utils.cpp
  src/stru_multi/4C_stru_multi_microstatic.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_multiscale.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Labels: team: discretization

#1270 Extract rebalancing from mesh input
  src/beaminteraction/src/4C_beaminteraction_str_model_evaluator.cpp
  src/core/binstrategy/4C_binstrategy.cpp
  src/core/binstrategy/4C_binstrategy_utils.cpp
  src/core/fem/src/condition/4C_fem_condition_point_coupling_redistribution.cpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
  src/core/rebalance/src/4C_rebalance.cpp
  src/core/rebalance/src/4C_rebalance.hpp
  src/core/rebalance/src/4C_rebalance_binning_based.cpp
  src/core/rebalance/src/4C_rebalance_print.cpp
  src/core/rebalance/src/4C_rebalance_print.hpp
  src/global_data/4C_global_data_read.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.cpp
  src/red_airways/4C_red_airways_implicitintegration.cpp
  src/scatra/4C_scatra_timint_heterogeneous_reaction_strategy.cpp
  src/ssi/4C_ssi_dyn.cpp
  src/xfem/4C_xfem_discretization_utils.cpp
Labels: type: clean code, team: discretization, team: input

#1276 Remove a few functions from Discretization
  src/core/fem/src/discretization/4C_fem_discretization.cpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_partition.cpp
  src/fluid/4C_fluid_utils.cpp
  src/levelset/4C_levelset_algorithm_utils.cpp
  src/scatra/4C_scatra_timint_implicit_service.cpp
Labels: type: clean code

#1279 Pass node coordinates explictly to Discretization
  cmake/setup_tests.cmake
  src/beamcontact/4C_beamcontact_beam3contact_manager.cpp
  src/beaminteraction/src/4C_beaminteraction_crosslinker_handler.cpp
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp
  src/constraint/4C_constraint_multipointconstraint2.cpp
  src/constraint/4C_constraint_multipointconstraint3.cpp
  src/constraint/4C_constraint_multipointconstraint3penalty.cpp
  src/contact/src/4C_contact_interface.cpp
  src/contact/src/4C_contact_interface_roundrobin.cpp
  src/contact/tests/4C_contact_element_reference_configuration_test.cpp
  src/core/binstrategy/4C_binstrategy.cpp
  src/core/fem/src/discretization/4C_fem_discretization.cpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_faces.cpp
  src/core/fem/src/discretization/4C_fem_discretization_fillcomplete.cpp
  src/core/fem/src/general/element/4C_fem_general_element_integration.hpp
  src/core/fem/src/general/node/4C_fem_general_node.cpp
  src/core/fem/src/general/node/4C_fem_general_node.hpp
  src/core/fem/src/general/utils/4C_fem_general_utils_createdis.cpp
  src/core/fem/src/general/utils/4C_fem_general_utils_createdis.hpp
  src/core/fem/src/geometry/4C_fem_geometry_periodic_boundingbox.cpp
  src/core/io/src/4C_io_gridgenerator.cpp
  src/core/io/src/4C_io_meshreader.cpp
  src/coupling/src/volmortar/4C_coupling_volmortar.cpp
  src/fluid/4C_fluid_discret_extractor.cpp
  src/fluid/4C_fluid_xwall.cpp
  src/mortar/src/4C_mortar_coupling2d.cpp
  src/mortar/src/4C_mortar_interface.cpp
  src/particle_wall/4C_particle_wall.cpp
  src/reduced_lung/src/4C_reduced_lung_main.cpp
  src/solid_3D_ele/4C_solid_3D_ele_nullspace.hpp
  src/xfem/4C_xfem_coupling_mesh.cpp
  src/xfem/4C_xfem_discretization_utils.cpp
  src/xfem/4C_xfem_multi_field_mapextractor.cpp
  tests/benchmark_tests/solid_3D_ele/4C_solid_3D_ele_evaluation_benchmark.cpp
  tests/install_test/CMakeLists.txt.in
  tests/install_test/main.cpp.in
  tests/install_test/test_install.sh.in
  unittests/beam3/4C_beam3_euler_bernoulli_test.cpp
  unittests/beam3/4C_beam3_kirchhoff_test.cpp
  unittests/beam3/4C_beam3_reissner_test.cpp
  unittests/common/unittest_utils/4C_unittest_utils_create_discretization_helper_test.hpp
  unittests/geometry_pair/4C_geometry_pair_line_to_surface_patch_geometry_test.hpp
  unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_geometry_functions_test.hpp
Labels: team: discretization

#1211 Write proper csv as DBC monitor output
  cmake/functions/four_c_testing_functions.cmake
  src/structure_new/src/4C_structure_new_integrator.cpp
  src/structure_new/src/4C_structure_new_timint_basedataio.cpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc.cpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc.hpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc_input.cpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc_input.hpp
  src/structure_new/src/utils/4C_structure_new_timint_basedataio_monitor_dbc.cpp
  src/structure_new/src/utils/4C_structure_new_timint_basedataio_monitor_dbc.hpp
  tests/input_files/beam3r_herm2line3_beam_to_beam_penalty_point_coupling_restart.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_gpts_deformation_gradient_3d_local_1.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_gpts_deformation_gradient_3d_local_2.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_gpts_deformation_gradient_3d_local_3.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_mortar_line2_line2_deformation_gradient_3d_general.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_mortar_line2_line2_deformation_gradient_3d_local_1.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_mortar_line4_line3_deformation_gradient_3d_cross_section.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_mortar_line4_line3_deformation_gradient_3d_general.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_volume_meshtying_rotational_coupling_mortar_line4_line3_deformation_gradient_3d_local_1.4C.yaml
  tests/input_files/beam3r_herm2line3_static_vdW_singlelengthsspec_smallsepapprox_simple_end_point_potential_reduction_strategy.4C.yaml
  tests/input_files/ref/beam3r_herm2line3_beam_to_beam_penalty_point_coupling_restart-101_monitor_dbc.yaml
  tests/input_files/ref/beam3r_herm2line3_static_vdW_singlelengthsspec_smallsepapprox_simple_end_point_potential_reduction_strategy_dbc_monitor_101.csv
  tests/input_files/ref/sohex8_dbc_monitor_10002.csv
  tests/input_files/sohex8_dbc_monitor.4C.yaml
  tests/list_of_tests.cmake
  utilities/diff_with_tolerance.py
Labels: team: output, breaking change

#1291 Add benchmark for FlatVectorVector
  src/core/utils/benchmark_tests/stl_extension/4C_utils_flat_vector_vector_benchmark.cpp
  src/core/utils/benchmark_tests/stl_extension/CMakeLists.txt
Labels: type: enhancement

#1283 Use Discretization dim for nodes
  src/art_net/4C_art_net_artery_ele_calc.cpp
  src/contact/src/4C_contact_interface.cpp
  src/contact/src/4C_contact_meshtying_abstract_strategy.cpp
  src/core/binstrategy/4C_binstrategy_utils.cpp
  src/core/fem/src/discretization/4C_fem_discretization.cpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/fem/src/discretization/4C_fem_discretization_nullspace.cpp
  src/core/fem/src/discretization/4C_fem_discretization_partition.cpp
  src/core/fem/src/general/element/4C_fem_general_element.cpp
  src/core/fem/src/general/element/4C_fem_general_element.hpp
  src/core/fem/src/general/element/4C_fem_general_element_center.cpp
  src/core/fem/src/general/node/4C_fem_general_node.cpp
  src/core/fem/src/general/node/4C_fem_general_node.hpp
  src/core/fem/src/geometry/4C_fem_geometry_searchtree_service.cpp
  src/core/geometric_search/src/4C_geometric_search_matchingoctree.cpp
  src/core/geometric_search/src/4C_geometric_search_matchingoctree.hpp
  src/core/io/src/4C_io_element_append_visualization.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/coupling/src/volmortar/4C_coupling_volmortar.cpp
  src/coupling/src/volmortar/4C_coupling_volmortar_integrator.cpp
  src/coupling/src/volmortar/4C_coupling_volmortar_shape.hpp
  src/fpsi/4C_fpsi_utils.cpp
  src/mortar/src/4C_mortar_element.cpp
  src/mortar/src/4C_mortar_interface.cpp
  src/mortar/src/4C_mortar_node.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.cpp
  src/post/4C_post_ensight_writer.cpp
  src/scatra/4C_scatra_functions.cpp
  src/scatra/4C_scatra_timint_implicit.cpp
  src/solid_3D_ele/4C_solid_3D_ele_nullspace.hpp
  src/structure/4C_structure_timint.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_meshtying.cpp
  tests/input_files/one_d_3_artery_network.4C.yaml
Labels: team: discretization

#1302 Move expensive InputSpecBuilders
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_input_spec_builders.templates.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
Labels: type: clean code

#1323 Allow to filter Mesh input
  src/core/fem/src/discretization/4C_fem_discretization.cpp
  src/core/fem/src/discretization/4C_fem_discretization.hpp
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/src/4C_io_exodus.hpp
  src/core/io/src/4C_io_mesh.cpp
  src/core/io/src/4C_io_mesh.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
  src/core/io/src/4C_io_vtu_reader.cpp
  src/core/io/src/4C_io_vtu_reader.hpp
  src/core/io/tests/4C_io_exodus_test.cpp
  src/core/io/tests/4C_io_mesh_test.cpp
  src/core/io/tests/4C_io_vtu_test.cpp
  src/core/utils/src/stl_extension/4C_utils_owner_or_view.hpp
  src/global_data/4C_global_data_read.cpp
Labels: team: discretization, team: input

#1333 Use a struct for rebalance parameters
  src/core/rebalance/src/4C_rebalance.cpp
  src/core/rebalance/src/4C_rebalance.hpp
  src/core/rebalance/src/4C_rebalance_input.cpp
  src/global_data/4C_global_data.hpp
  src/global_data/4C_global_data_read.cpp
Labels: type: clean code, team: input
