Repository 4C-multiphysics/4C, pull requests merged in 2025-07, with the labels that each got.

#907 No longer accept .dat input
  apps/global_full/4C_global_full_control.cpp
  cmake/functions/four_c_testing_functions.cmake
  tests/input_files/ale2d_laplace_material.4C.yaml
  tests/input_files/ale2d_laplace_material.dat
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_surface_volume_coupling_mortar.4C.yaml
  tests/input_files/beam3r_herm2line3_static_beam_to_solid_surface_volume_coupling_mortar.dat
  tests/input_files/constr3D_MPC_direct.4C.yaml
  tests/input_files/constr3D_MPC_direct.dat
  tests/input_files/contact2D_onlylin_stdlagr.4C.yaml
  tests/input_files/contact2D_onlylin_stdlagr.dat
  tests/input_files/contact2D_simpler.4C.yaml
  tests/input_files/contact2D_simpler.dat
  tests/input_files/contact3D_pwlin_penalty_hex20.4C.yaml
  tests/input_files/contact3D_pwlin_penalty_hex20.dat
  tests/input_files/contact3D_pwlin_penalty_hex27.4C.yaml
  tests/input_files/contact3D_pwlin_penalty_hex27.dat
  tests/input_files/orthopressure_solidw6.4C.yaml
  tests/input_files/orthopressure_solidw6.dat
  tests/input_files/particle_nointer_3d_pbc_xyz_initvel_velocityverlet.4C.yaml
  tests/input_files/particle_nointer_3d_pbc_xyz_initvel_velocityverlet.dat
  tests/input_files/poro_3D_hex8.4C.yaml
  tests/input_files/poro_3D_hex8.dat
  tests/input_files/poro_3D_hex8_new_struc.4C.yaml
  tests/input_files/poro_3D_hex8_new_struc.dat
  tests/input_files/poro_solid_nitsche_contact3D_twoelem_wonopen_new_struc.4C.yaml
  tests/input_files/poro_solid_nitsche_contact3D_twoelem_wonopen_new_struc.dat
  tests/input_files/soshw6_thin_nonlinear_pinched_hemisphere.4C.yaml
  tests/input_files/soshw6_thin_nonlinear_pinched_hemisphere.dat
  tests/input_files/sotet10_cooks_nl.4C.yaml
  tests/input_files/sotet10_cooks_nl.dat
  tests/input_files/strufem_tet10_disp_cantilever.4C.yaml
  tests/input_files/strufem_tet10_disp_cantilever.dat
  tests/input_files/strufem_tet4_disp_cantilever.4C.yaml
  tests/input_files/strufem_tet4_disp_cantilever.dat
  tests/input_files/strufem_wedge6_disp_cantilever.4C.yaml
  tests/input_files/strufem_wedge6_disp_cantilever.dat
  tests/input_files/w1q4_cantilever_eas.4C.yaml
  tests/input_files/w1q4_cantilever_eas.dat
  tests/input_files/w1q4_patch_eas.4C.yaml
  tests/input_files/w1q4_patch_eas.dat
  tests/input_files/w1q8_patch_nonlinear.4C.yaml
  tests/input_files/w1q8_patch_nonlinear.dat
  tests/input_files/w1q9_dyn_rot_drt_gena.4C.yaml
  tests/input_files/w1q9_dyn_rot_drt_gena.dat
  tests/input_files/w1t6_patch_linear.4C.yaml
  tests/input_files/w1t6_patch_linear.dat
  tests/input_files/xfsi_3D_boxes.4C.yaml
  tests/input_files/xfsi_3D_boxes.dat
  tests/list_of_tests.cmake
Labels: team: input, breaking change

#939 Input: remove redefinition of node counts
  apps/global_full/4C_global_full_main.cpp
  src/ale/4C_ale_ale2.cpp
  src/ale/4C_ale_ale3.cpp
  src/art_net/4C_art_net_artery.cpp
  src/beam3/4C_beam3_euler_bernoulli.cpp
  src/beam3/4C_beam3_kirchhoff.cpp
  src/beam3/4C_beam3_reissner.cpp
  src/bele/4C_bele_bele3.cpp
  src/bele/4C_bele_vele3.cpp
  src/core/fem/src/general/element/4C_fem_general_element.cpp
  src/core/fem/src/general/element/4C_fem_general_element.hpp
  src/core/io/src/4C_io_gridgenerator.cpp
  src/core/io/src/4C_io_input_file.cpp
  src/core/io/src/4C_io_input_file.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/fluid_ele/4C_fluid_ele.cpp
  src/fluid_ele/4C_fluid_ele_xwall.cpp
  src/global_data/4C_global_data_read.cpp
  src/global_data/4C_global_data_read.hpp
  src/lubrication/src/4C_lubrication_ele.cpp
  src/membrane/4C_membrane_eletypes.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele.cpp
  src/red_airways/4C_red_airways_acinus.cpp
  src/red_airways/4C_red_airways_airway.cpp
  src/red_airways/4C_red_airways_interacinardep.cpp
  src/rigidsphere/4C_rigidsphere.cpp
  src/scatra_ele/4C_scatra_ele.cpp
  src/shell7p/4C_shell7p_ele.cpp
  src/shell7p/4C_shell7p_ele_scatra.cpp
  src/shell_kl_nurbs/src/4C_shell_kl_nurbs.cpp
  src/solid_3D_ele/4C_solid_3D_ele.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_based.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based.cpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_p1.cpp
  src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele.cpp
  src/thermo/src/element/4C_thermo_element.cpp
  src/torsion3/4C_torsion3.cpp
  src/truss3/4C_truss3.cpp
  src/w1/4C_w1.cpp
  src/w1/4C_w1_nurbs.cpp
Labels: team: input

#962 YAML: quoted values can only be strings
  src/core/io/src/4C_io_yaml.cpp
  src/core/io/tests/4C_io_input_spec_test.cpp
Labels: type: bug report, team: input

#977 Refactor global_full as a step towards enabling actual modules
  apps/global_full/4C_global_full_control.cpp
  apps/global_full/4C_global_full_entrypoint_switch.cpp
  apps/global_full/4C_global_full_init_control.cpp
  apps/global_full/4C_global_full_init_control.hpp
  apps/global_full/4C_global_full_inp_control.cpp
  apps/global_full/4C_global_full_inp_control.hpp
  apps/global_full/4C_global_full_io.cpp
  apps/global_full/4C_global_full_io.hpp
  apps/global_full/4C_global_full_main.cpp
  apps/global_full/CMakeLists.txt
  cmake/functions/four_c_testing_functions.cmake
  src/core/comm/src/4C_comm_utils.cpp
  src/core/comm/src/4C_comm_utils.hpp
  src/core/comm/tests/4C_comm_utils_test.np3.cpp
  tests/input_files/sohex8_multiscale_macro.4C.yaml
  tests/input_files/sohex8_multiscale_macro_2micro.4C.yaml
  tests/input_files/sohex8_multiscale_macro_eas.4C.yaml
  tests/input_files/sohex8_multiscale_macro_plastic.4C.yaml
Labels: taskforce: modularization

#985 Fix include style pre-commit hook
  utilities/four_c_utils/src/four_c_utils/check_includes.py
Labels: type: bug report, team: infrastructure

#983 InputSpec for SymbolicExpression
  src/core/io/src/4C_io_input_spec_builders.cpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_input_spec_storage.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
  src/core/utils/src/functions/4C_utils_symbolic_expression.hpp
Labels: team: input

#989 Exodus reader always checks for errors
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/src/4C_io_exodus.hpp
Labels: team: input

#987 Make Exporter work for unordered_map
  src/core/comm/src/4C_comm_exporter.hpp
Labels: team: discretization

#990 Remove FE::Utils namespace
  src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
  src/core/fem/src/discretization/4C_fem_discretization_faces.cpp
  src/core/fem/src/discretization/4C_fem_discretization_hdg.cpp
  src/core/fem/src/discretization/4C_fem_discretization_hdg.hpp
  src/core/fem/src/discretization/4C_fem_discretization_utils.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils.hpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_dbc.cpp
  src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp
  src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization.cpp
  src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization.hpp
  src/fluid/4C_fluid_DbcHDG.cpp
  src/fluid/4C_fluid_DbcHDG.hpp
  src/fluid/4C_fluid_implicit_integration.cpp
  src/structure/4C_structure_timint.cpp
  src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp
  src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Labels: type: clean code

#1007 Fix: remove unused poro inpar file
  src/inpar/4C_inpar_poro.hpp
  src/inpar/4C_inpar_poroscatra.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_based.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based_p1.hpp
  src/solid_poro_3D_ele/4C_solid_poro_3D_ele_properties.hpp
Labels: type: clean code

#1008 Move files from inpar to physics
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_conditions.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_params_base.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_contact_params.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_meshtying_pair_mortar_FAD.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_meshtying_pair_mortar_FAD.hpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_surface_meshtying_params.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_volume_meshtying_pair_2d-3d_base.cpp
  src/beaminteraction/src/4C_beaminteraction_beam_to_solid_volume_meshtying_params.cpp
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_beamcontact.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_input.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_input.hpp
  src/core/rebalance/src/4C_rebalance_input.cpp
  src/core/rebalance/src/4C_rebalance_input.hpp
  src/ehl/4C_ehl_monolithic.cpp
  src/fbi/4C_fbi_beam_to_fluid_meshtying_params.cpp
  src/fbi/4C_fbi_input.cpp
  src/geometry_pair/4C_geometry_pair_element_faces.cpp
  src/geometry_pair/4C_geometry_pair_element_faces.hpp
  src/geometry_pair/4C_geometry_pair_factory.cpp
  src/geometry_pair/4C_geometry_pair_input.cpp
  src/geometry_pair/4C_geometry_pair_input.hpp
  src/geometry_pair/4C_geometry_pair_line_projection.cpp
  src/geometry_pair/4C_geometry_pair_line_to_3D_evaluation_data.cpp
  src/geometry_pair/4C_geometry_pair_line_to_3D_evaluation_data.hpp
  src/geometry_pair/4C_geometry_pair_line_to_surface_evaluation_data.cpp
  src/geometry_pair/4C_geometry_pair_line_to_surface_evaluation_data.hpp
  src/global_legacy_module/4C_global_legacy_module_validparameters.cpp
  src/inpar/4C_inpar_beam_to_solid.cpp
  src/inpar/4C_inpar_cardiac_monodomain.hpp
  src/inpar/4C_inpar_geometry_pair.hpp
  src/inpar/4C_inpar_solver_nonlin.hpp
  src/loma/4C_loma_algorithm.cpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_artery_coupling.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic.hpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_input.cpp
  src/solver_nonlin_nox/4C_solver_nonlin_nox_input.hpp
  unittests/beaminteraction/4C_beaminteraction_beam_to_solid_volume_meshtying_mortar_test.cpp
  unittests/fbi/4C_beam_to_fluid_meshtying_pair_gauss_point_test.cpp
  unittests/geometry_pair/4C_geometry_pair_line_to_surface_test.cpp
  unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_test.cpp
Labels: taskforce: modularization

#1015 Move fluid turbulence input
  src/fluid/4C_fluid_implicit_integration.cpp
  src/fluid/4C_fluid_implicit_integration.hpp
  src/fluid/4C_fluid_timint_bdf2.cpp
  src/fluid/4C_fluid_timint_genalpha.cpp
  src/fluid/4C_fluid_timint_ost.cpp
  src/fluid_ele/4C_fluid_ele_calc.cpp
  src/fluid_ele/4C_fluid_ele_evaluate_utils.hpp
  src/fluid_ele/4C_fluid_ele_parameter.cpp
  src/fluid_ele/4C_fluid_ele_parameter.hpp
  src/fluid_turbulence/4C_fluid_turbulence_input.hpp
  src/inpar/4C_inpar_turbulence.hpp
  src/scatra_ele/4C_scatra_ele_calc_service_turbulence.cpp
  src/scatra_ele/4C_scatra_ele_parameter_turbulence.cpp
  src/scatra_ele/4C_scatra_ele_parameter_turbulence.hpp
Labels: type: clean code, team: input
