Repository 4C-multiphysics/4C, pull requests merged in 2025-04, with the labels that each got.

#593 CMake: configuration of supported versions of a dependency
  CMakeLists.txt
  apps/global_full/4C_global_full_main.cpp
  cmake/configure/configure_Trilinos.cmake
  cmake/functions/four_c_configure_dependency.cmake
  cmake/functions/four_c_get_trilinos_version.cmake
  dependencies/supported_version/Trilinos.txt
  src/config/4C_config_trilinos_version.hpp.in
  src/config/CMakeLists.txt
Labels: team: infrastructure

#599 Remove a few InputParameterContainer includes
  apps/post_monitor/4C_post_monitor.hpp
  src/ale/4C_ale_resulttest.cpp
  src/art_net/4C_art_net_artery_resulttest.cpp
  src/core/fem/src/general/element/4C_fem_general_element.hpp
  src/core/io/src/4C_io_gridgenerator.cpp
  src/core/utils/src/result_test/4C_utils_result_test.cpp
  src/core/utils/src/result_test/4C_utils_result_test.hpp
  src/fsi/src/utils/4C_fsi_resulttest.cpp
  src/lubrication/src/4C_lubrication_resulttest.cpp
  src/membrane/4C_membrane_scatra.cpp
  src/particle_algorithm/4C_particle_algorithm_result_test.cpp
  src/particle_rigidbody/4C_particle_rigidbody_result_test.cpp
  src/particle_wall/4C_particle_wall_result_test.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_resulttest.cpp
  src/red_airways/4C_red_airways_resulttest.cpp
  src/rigidsphere/4C_rigidsphere_input.cpp
  src/solid_3D_ele/4C_solid_3D_ele_line.cpp
  src/ssti/4C_ssti_resulttest.cpp
  src/sti/4C_sti_resulttest.cpp
  src/structure/4C_structure_resulttest.cpp
  src/structure_new/src/utils/4C_structure_new_resulttest.cpp
  src/thermo/src/utils/4C_thermo_resulttest.cpp
Labels: type: clean code, team: infrastructure

#601 Warn when using a dat file in a 4C run
  apps/global_full/4C_global_full_control.cpp
Labels: team: input

#588 InputSpec: refactor internals and add better errors
  src/core/io/src/4C_io_input_file.cpp
  src/core/io/src/4C_io_input_spec.cpp
  src/core/io/src/4C_io_input_spec.hpp
  src/core/io/src/4C_io_input_spec_builders.cpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
Labels: type: enhancement, team: input

#613 Remove unnecessary Teuchos includes
  src/ale/4C_ale_input.cpp
  src/beamcontact/4C_beamcontact_input.cpp
  src/beaminteraction/src/potential/4C_beaminteraction_potential_input.cpp
  src/browniandyn/4C_browniandyn_input.cpp
  src/contact/4C_contact_input.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp
  src/core/utils/src/parameters/4C_utils_parameter_list.hpp
  src/cut/4C_cut_input.cpp
  src/ehl/4C_ehl_input.cpp
  src/fbi/4C_fbi_input.cpp
  src/inpar/4C_inpar_IO_monitor_structure_dbc.cpp
  src/inpar/4C_inpar_IO_runtime_output.cpp
  src/inpar/4C_inpar_IO_runtime_output_fluid.cpp
  src/inpar/4C_inpar_IO_runtime_output_structure_beams.cpp
  src/inpar/4C_inpar_IO_runtime_vtk_output_structure.cpp
  src/inpar/4C_inpar_IO_runtime_vtp_output_structure.cpp
  src/inpar/4C_inpar_beam_to_solid.cpp
  src/inpar/4C_inpar_beaminteraction.cpp
  src/inpar/4C_inpar_binningstrategy.cpp
  src/inpar/4C_inpar_bio.cpp
  src/inpar/4C_inpar_cardiac_monodomain.cpp
  src/inpar/4C_inpar_cardiovascular0d.cpp
  src/inpar/4C_inpar_constraint_framework.cpp
  src/inpar/4C_inpar_elch.cpp
  src/inpar/4C_inpar_fluid.cpp
  src/inpar/4C_inpar_fpsi.cpp
  src/inpar/4C_inpar_fs3i.cpp
  src/inpar/4C_inpar_fsi.cpp
  src/inpar/4C_inpar_geometry_pair.cpp
  src/inpar/4C_inpar_io.cpp
  src/inpar/4C_inpar_levelset.cpp
  src/inpar/4C_inpar_mortar.cpp
  src/inpar/4C_inpar_particle.cpp
  src/inpar/4C_inpar_pasi.cpp
  src/inpar/4C_inpar_plasticity.cpp
  src/inpar/4C_inpar_poroelast.cpp
  src/inpar/4C_inpar_poroscatra.cpp
  src/inpar/4C_inpar_problemtype.cpp
  src/inpar/4C_inpar_rebalance.cpp
  src/inpar/4C_inpar_s2i.cpp
  src/inpar/4C_inpar_scatra.cpp
  src/inpar/4C_inpar_searchtree.cpp
  src/inpar/4C_inpar_solver_nonlin.cpp
  src/inpar/4C_inpar_ssi.cpp
  src/inpar/4C_inpar_ssti.cpp
  src/inpar/4C_inpar_sti.cpp
  src/inpar/4C_inpar_structure.cpp
  src/inpar/4C_inpar_tsi.cpp
  src/inpar/4C_inpar_volmortar.cpp
  src/inpar/4C_inpar_wear.cpp
  src/inpar/4C_inpar_xfem.cpp
  src/lubrication/src/4C_lubrication_input.cpp
  src/poroelast_scatra/4C_poroelast_scatra_monolithic.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_input.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_input.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_input.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic_twoway.cpp
  src/thermo/src/utils/4C_thermo_input.cpp
Labels: type: clean code

#615 Resolve one header-in-header include
  src/adapter/4C_adapter_coupling_ehl_mortar.cpp
  src/constraint/4C_constraint_penalty.cpp
  src/contact/4C_contact_interface.cpp
  src/contact/4C_contact_interface_assemble.cpp
  src/contact/4C_contact_lagrange_strategy.cpp
  src/contact/4C_contact_lagrange_strategy_poro.cpp
  src/contact/4C_contact_lagrange_strategy_tsi.cpp
  src/contact/4C_contact_lagrange_strategy_wear.cpp
  src/contact/4C_contact_manager.cpp
  src/contact/4C_contact_meshtying_manager.cpp
  src/contact/4C_contact_nitsche_strategy_ssi.cpp
  src/contact/4C_contact_penalty_strategy.cpp
  src/contact/4C_contact_tsi_interface.cpp
  src/contact/4C_contact_wear_interface.cpp
  src/contact/4C_contact_wear_interface_tools.cpp
  src/core/binstrategy/4C_binstrategy_utils.cpp
  src/core/comm/src/4C_comm_utils_factory.hpp
  src/core/fem/src/condition/4C_fem_condition_utils.cpp
  src/core/io/src/4C_io_elementreader.cpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/fluid_turbulence/4C_fluid_turbulence_transfer_turb_inflow.hpp
  src/mat/4C_mat_micromaterial_evaluate.cpp
  src/particle_engine/4C_particle_engine.cpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_linebased.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_nodetopoint.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_surfbased.cpp
  src/porofluid_pressure_based_ele/4C_porofluid_pressure_based_ele.cpp
  src/shell7p/4C_shell7p_utils.cpp
  src/structure/4C_structure_timint_ab2.cpp
  src/structure/4C_structure_timint_centrdiff.cpp
  src/structure/4C_structure_timint_expl.cpp
  src/structure/4C_structure_timint_expleuler.cpp
  src/structure_new/src/output/4C_structure_new_gauss_point_data_output_manager.hpp
  src/xfem/4C_xfem_xfield_field_coupling.cpp
Labels: type: clean code

#618 [CMake] Simplifiy installation logic
  cmake/configure/configure_ArborX.cmake
  cmake/configure/configure_Backtrace.cmake
  cmake/configure/configure_CLN.cmake
  cmake/configure/configure_FFTW.cmake
  cmake/configure/configure_MIRCO.cmake
  cmake/configure/configure_Qhull.cmake
  cmake/configure/configure_magic_enum.cmake
  cmake/configure/configure_ryml.cmake
  cmake/setup_install.cmake
  cmake/templates/4CTargets.cmake.in
Labels: type: clean code, team: infrastructure

#620 Clean up boost dependency
  apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp
  apps/create_rtdfiles/4C_create_rtdfiles_wrapper.cpp
  cmake/configure/configure_Boost.cmake
  src/constraint_framework/4C_constraint_framework_submodelevaluator_mpc.hpp
  src/core/linalg/src/sparse/4C_linalg_view.hpp
  src/core/utils/src/string_utils/4C_utils_string.cpp
  src/core/utils/src/string_utils/4C_utils_string.hpp
  src/cut/4C_cut_find_cycles.hpp
  src/cut/4C_cut_pointgraph.cpp
Labels: type: clean code

#623 Add post setup call to StructPoro material
  src/mat/4C_mat_structporo.cpp
  src/mat/4C_mat_structporo.hpp
Labels: team: poro

#625 Fix bug in --to-yaml
  apps/global_full/4C_global_full_main.cpp
Labels: team: infrastructure

#603 Validate size read from_parameter for yaml files
  src/core/io/src/4C_io_input_spec_builders.cpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/tests/4C_io_input_spec_test.cpp
Labels: team: input

#595 Clean up and improve docs on 4C installation
  doc/documentation/installation.rst
Labels: team: infrastructure

#627 Switch ssti input files from dat to yaml
  tests/input_files/ssti_mono_3D_2blocks_elch_temp_dep_diff.4C.yaml
  tests/input_files/ssti_mono_3D_2blocks_elch_temp_dep_diff.dat
  tests/input_files/ssti_mono_3D_3hex8_elch_s2i_butlervolmerthermo_growthlaw.4C.yaml
  tests/input_files/ssti_mono_3D_3hex8_elch_s2i_butlervolmerthermo_growthlaw.dat
  tests/input_files/ssti_mono_3D_6hex8_elch_s2i_butlervolmerthermo_BGS-AMG_3x3.4C.yaml
  tests/input_files/ssti_mono_3D_6hex8_elch_s2i_butlervolmerthermo_BGS-AMG_3x3.dat
  tests/input_files/ssti_mono_3D_6hex8_elch_s2i_butlervolmerthermo_cycling.4C.yaml
  tests/input_files/ssti_mono_3D_6hex8_elch_s2i_butlervolmerthermo_cycling.dat
  tests/input_files/ssti_mono_3D_tet4_batt_with_anode_plate_and_current_collectors_elch_s2i_butlervolmer_BGS_AMG_11x11.4C.yaml
  tests/input_files/ssti_mono_3D_tet4_batt_with_anode_plate_and_current_collectors_elch_s2i_butlervolmer_BGS_AMG_11x11.dat
  tests/list_of_tests.cmake
Labels: team: input, team: scatra, team: structure

#632 Migrate pre_exodus to yaml
  apps/pre_exodus/4C_pre_exodus.cpp
  apps/pre_exodus/4C_pre_exodus_readbc.cpp
  apps/pre_exodus/4C_pre_exodus_readbc.hpp
  apps/pre_exodus/4C_pre_exodus_validate.cpp
  apps/pre_exodus/4C_pre_exodus_validate.hpp
  apps/pre_exodus/4C_pre_exodus_writedat.cpp
  apps/pre_exodus/4C_pre_exodus_writedat.hpp
  cmake/functions/four_c_testing_functions.cmake
  tests/framework-test/tutorial_battery.head
  tests/framework-test/tutorial_contact_3d.head
  tests/framework-test/tutorial_fluid.head
  tests/framework-test/tutorial_fsi.head
  tests/framework-test/tutorial_fsi_3d.head
  tests/framework-test/tutorial_solid.head
  tests/list_of_tests.cmake
Labels: team: input, breaking change

#633 Remove an unused member in Structure::TimInt
  src/structure/4C_structure_timint.cpp
  src/structure/4C_structure_timint.hpp
Labels: type: clean code

#634 Remove various helpers to dump dat style content
  apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp
  apps/global_full/4C_global_full_inp_control.cpp
  apps/global_full/4C_global_full_main.cpp
  src/core/fem/src/general/element/4C_fem_general_element_definition.cpp
  src/core/fem/src/general/element/4C_fem_general_element_definition.hpp
  src/core/io/src/4C_io_input_file_utils.cpp
  src/core/io/src/4C_io_input_file_utils.hpp
  src/global_data/4C_global_data.cpp
  src/global_data/4C_global_data.hpp
  src/inpar/4C_inpar_validconditions.cpp
  src/inpar/4C_inpar_validconditions.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/inpar/4C_inpar_validparameters.hpp
Labels: type: clean code, team: input

#638 Rewrite a loop that triggers a compiler warning with UBSAN
  src/core/binstrategy/4C_binstrategy_utils.cpp
Labels: type: clean code

#631 Docker: don't use a separate image for deal.II
  .github/workflows/buildtest.yml
  .github/workflows/checkcode.yml
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly_tests.yml
  dependencies/current/dealii/install.sh
  docker/dependencies/Dockerfile
  docker/dependencies_dealii/Dockerfile
  docker/dependencies_dealii/compute_dependencies_hash.sh
Labels: team: infrastructure

#639 Remove dead code in exodus reader
  apps/pre_exodus/4C_pre_exodus.cpp
  apps/pre_exodus/4C_pre_exodus_reader.cpp
  apps/pre_exodus/4C_pre_exodus_reader.hpp
Labels: type: clean code, team: input

#641 CMake: only copy testing support files
  cmake/functions/four_c_auto_define_tests.cmake
  src/core/io/tests/test_files/has_includes/folder2/include2.dat.in
Labels: type: bug report, team: infrastructure

#642 Cmake: copy arbitray number of support files for framework tests
  cmake/functions/four_c_testing_functions.cmake
  tests/list_of_tests.cmake
Labels: team: infrastructure

#643 Fix bug in structure micro-micro
  src/mat/4C_mat_micromaterial.cpp
  src/mat/4C_mat_micromaterial.hpp
  src/mat/4C_mat_micromaterial_evaluate.cpp
  src/mat/4C_mat_micromaterialgp_static.cpp
  src/structure/4C_structure_dyn_nln_drt.cpp
  tests/input_files/sohex8_multiscale_macro.dat
Labels: priority: high

#646 Throw if iterative linear solver does not converge
  src/core/linear_solver/src/method/4C_linear_solver_method_iterative.cpp
  src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp
  src/inpar/4C_inpar_solver.cpp
  tests/input_files/consinter3D_tsi_hex8_tet4.dat
  tests/input_files/f2_channel_EOS_quad4_1000x10_quad_inflow_h_diam_to_opp.dat
  tests/input_files/f2_channel_EOS_quad4_200x10_cubic_inflow.dat
  tests/input_files/f2_drivencavity32x32_Re1000_stat.dat
  tests/input_files/f3_beltrami_tet10_hdg.dat
  tests/input_files/f3_cha_8x8x8_recongradl2.dat
  tests/input_files/f3_cha_8x8x8_recongradspr.dat
  tests/input_files/f3_decaying_hit_8x8x8.dat
  tests/input_files/f3_decaying_hit_eb.dat
  tests/input_files/f3_impl_channel_pressuregrad.dat
  tests/input_files/f3_periodic_hill_w_forcing_24x12x12.dat
  tests/input_files/f3_womersley.dat
  tests/input_files/fsi_dc_mono_mtrss_ada_ab2_none.dat
  tests/input_files/scatra_forced_hit_iso_8x8x8_dsm.dat
  tests/input_files/sti_mono_2D_quad4_elch_s2i_butlervolmerpeltier_diabatic_AMG_vectorbased.dat
  tests/input_files/volmortar3D_tsi_hex8_tet4.dat
  tests/input_files/xfluid_stat_sliver_cut_instat.dat
  tests/input_files/xfluid_taylor_couette_NavSlip_eps1.0_25x25_krylov_levelset_altgeogeneration.dat
  tests/input_files/xfluid_taylor_couette_NavSlip_ri0.19_ro0.49_epsi1.0_epso1e-5_ti-2.5_to0.5_8x8_levelset_hex27.dat
Labels: breaking change

#649 Allow non-required section in input files
  src/core/io/src/4C_io_input_file.cpp
  src/core/io/src/4C_io_input_file.hpp
  src/core/io/src/4C_io_input_file_utils.cpp
Labels: team: input

#647 Add a basic test for exodus mesh
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/tests/4C_io_exodus_test.cpp
  src/core/io/tests/test_files/exodus/cube.exo
Labels: team: input

#650 Split rebalancing into more useful parts
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
Labels: team: discretization, team: input

#652 Support mesh input from exodus files
  apps/global_full/4C_global_full_inp_control.cpp
  apps/pre_exodus/4C_pre_exodus_validate.cpp
  src/core/fem/src/condition/4C_fem_condition.cpp
  src/core/fem/src/condition/4C_fem_condition.hpp
  src/core/fem/src/condition/4C_fem_condition_definition.cpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
  src/core/io/tests/4C_io_exodus_test.cpp
  src/global_data/4C_global_data_read.cpp
  src/global_data/4C_global_data_read.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/ssi/4C_ssi_base.cpp
  src/structure_new/src/utils/4C_structure_new_monitor_dbc.cpp
  tests/input_files/contact3D_exodus_in.4C.yaml
  tests/input_files/contact3D_exodus_in.exo
  tests/list_of_tests.cmake
Labels: team: input

#657 Simplify mesh reading
  apps/pre_exodus/4C_pre_exodus_writedat.cpp
  src/core/io/src/4C_io_elementreader.cpp
  src/core/io/src/4C_io_elementreader.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
  src/core/io/src/4C_io_nodereader.cpp
  src/core/io/src/4C_io_nodereader.hpp
  src/global_data/4C_global_data_read.cpp
Labels: type: clean code, team: input

#660 Unify input of discretizations
  src/core/fem/src/general/utils/4C_fem_general_utils_createdis.cpp
  src/core/io/src/4C_io_meshreader.cpp
  src/core/io/src/4C_io_meshreader.hpp
  src/global_data/4C_global_data_read.cpp
Labels: team: input

#670 Remove GEOMETRY input parameter
  src/core/io/src/4C_io_geometry_type.hpp
  src/core/io/src/4C_io_meshreader.hpp
  src/global_data/4C_global_data_read.cpp
  src/inpar/4C_inpar_IO_monitor_structure_dbc.cpp
  src/inpar/4C_inpar_IO_runtime_vtp_output_structure.cpp
  src/inpar/4C_inpar_fluid.cpp
  src/inpar/4C_inpar_structure.cpp
  src/thermo/src/utils/4C_thermo_input.cpp
  tests/input_files/contact3D_exodus_in.4C.yaml
  tests/input_files/f3_channel_EOS_hex8_10x10x10_quad_inflow_altgeogeneration.dat
  tests/input_files/f3_channel_EOS_wedge15_10x10x10_quad_inflow_altgeogeneration.dat
  tests/input_files/f3_forced_hit_geogen_hdg.dat
  tests/input_files/f3_kimmoin_stat_24x24x1_wedge15_pseudo2D.dat
  tests/input_files/f3_stokes_residualbased_rotboxgeom.dat
  tests/input_files/fbi_mortar_solidcoupling.dat
  tests/input_files/fsi_dc3D_part_ait_ga_ost_xwall.dat
  tests/input_files/homogenized-constrained-mixture-cyl-aniso-impl-nofibdir.dat
  tests/input_files/sohex8_disp_altgeogeneration.dat
  tests/input_files/tfsi_plate.dat
  tests/input_files/xfluid_couette_NavSlip_eps1.6_g-1.0_mu0.16_altgeogeneration_movingls_fully_weakly_verticalcut.dat
  tests/input_files/xfluid_couette_NavSlip_eps1.6_g-1.0_mu0.1_altgeogeneration.dat
  tests/input_files/xfluid_couette_NavSlip_eps1.6_g-1.0_mu0.1_altgeogeneration_wedge6.dat
  tests/input_files/xfluid_forward_facing_step_stationary_NavSlip_eps1.6_16x16_NIT_altgeogeneration.dat
  tests/input_files/xfluid_ls_neumann_inflow_stab.dat
  tests/input_files/xfluid_mesh_neumann_inflow_stab.dat
  tests/input_files/xfluid_moving_torus_NavSlip_vareps_levelset_psmoothed_8x8x16.dat
  tests/input_files/xfluid_oseen_urquiza_square_NavSlip_eps1.0_40x40_mesh_altgeogeneration.dat
  tests/input_files/xfluid_taylor_couette_NavSlip_eps1.0_25x25_krylov_levelset_altgeogeneration.dat
  tests/input_files/xfluid_taylor_couette_NavSlip_ri0.19_ro0.49_epsi1.0_epso1e-5_ti-2.5_to0.5_8x8_levelset_hex27.dat
  tests/input_files/xfpsci_twoelem_pp.dat
  tests/input_files/xfpsci_twoelem_ps.dat
  tests/input_files/xfsci_twoelem.dat
  tests/input_files/xfsi_3D_boxes.dat
Labels: team: input, breaking change

#678 Update documentation on doxygen
  doc/documentation/doxygen.rst
Labels: type: clean code

#677 Minor bugfixes in documentation
  doc/documentation/developer_cmake.rst
  doc/documentation/developer_dirstructure.rst
  doc/documentation/installation.rst
Labels: type: clean code

#679 Revert ArborX update
  cmake/configure/configure_ArborX.cmake
  src/beam3/4C_beam3_base.cpp
  src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_beamcontact.cpp
  src/core/fem/src/CMakeLists.txt
  src/core/fem/src/condition/4C_fem_condition_periodic.cpp
  src/core/fem/src/dofset/4C_fem_dofset_definedmapping_wrapper.cpp
  src/core/fem/src/dofset/4C_fem_dofset_merged_wrapper.cpp
  src/core/fem/src/general/element/4C_fem_general_element.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_bounding_volume.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_distributed_tree.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_distributed_tree.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_matchingoctree.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_matchingoctree.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_params.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_params.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_utils.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_utils.hpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_visualization.cpp
  src/core/fem/src/geometric_search/4C_fem_geometric_search_visualization.hpp
  src/core/fem/src/geometric_search/CMakeLists.txt
  src/core/fem/src/geometric_search/script/kdop_generate_possible_intersection_planes.wls
  src/core/fem/tests/CMakeLists.txt
  src/core/fem/tests/geometric_search/4C_fem_geometric_search_create_bounding_volumes_test.hpp
  src/core/fem/tests/geometric_search/4C_fem_geometric_search_distributed_test.np3.cpp
  src/core/fem/tests/geometric_search/4C_fem_geometric_search_test.cpp
  src/core/fem/tests/geometric_search/CMakeLists.txt
  src/core/geometric_search/src/CMakeLists.txt
  src/core/rebalance/src/4C_rebalance_binning_based.cpp
  src/core/rebalance/src/4C_rebalance_graph_based.cpp
  src/core/rebalance/src/4C_rebalance_graph_based.hpp
  src/coupling/src/adapter/4C_coupling_adapter.cpp
  src/fluid_turbulence/4C_fluid_turbulence_transfer_turb_inflow.cpp
  src/inpar/4C_inpar_geometric_search.cpp
  src/inpar/4C_inpar_geometric_search.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/rigidsphere/4C_rigidsphere_evaluate.cpp
  src/ssi/4C_ssi_utils.cpp
Labels: priority: high, type: bug report

#686 Update documentation on doxygen with an example
  doc/documentation/src/developer_guide/doxygen.rst
Labels: team: infrastructure

#691 Update testing docs
  doc/documentation/src/developer_guide/developmentguide.rst
  doc/documentation/src/developer_guide/testing.rst
Labels: team: infrastructure

#692 Update docs on naming conventions
  doc/documentation/src/developer_guide/codingguidelines.rst
Labels: team: infrastructure

#690 Clean up TSI input and define flags
  src/inpar/4C_inpar_plasticity.cpp
  src/inpar/4C_inpar_tsi.hpp
  src/inpar/4C_inpar_validparameters.cpp
  src/mat/4C_mat_damage.cpp
  src/mat/4C_mat_plastic_VarConstUpdate.hpp
  src/mat/4C_mat_plasticelasthyper.cpp
  src/mat/4C_mat_plasticelasthyper.hpp
  src/mat/4C_mat_plasticlinelast.cpp
  src/mat/4C_mat_robinson.cpp
  src/mat/4C_mat_thermoplastichyperelast.cpp
  src/mat/4C_mat_thermoplasticlinelast.cpp
  src/thermo/src/element/4C_thermo_ele_boundary_impl.cpp
  src/thermo/src/element/4C_thermo_ele_impl.cpp
  src/thermo/src/element/4C_thermo_ele_impl.hpp
  src/tsi/4C_tsi_algorithm.cpp
  src/tsi/4C_tsi_defines.hpp
  src/tsi/4C_tsi_dyn.cpp
  src/tsi/4C_tsi_input.cpp
  src/tsi/4C_tsi_input.hpp
  src/tsi/4C_tsi_monolithic.cpp
  src/tsi/4C_tsi_monolithic.hpp
  src/tsi/4C_tsi_partitioned.cpp
  src/tsi/4C_tsi_partitioned.hpp
Labels: type: clean code, team: thermo

#720 Replace assert with FOUR_C_ASSERT
  src/constraint/4C_constraint_springdashpot.cpp
Labels: type: clean code

#512 Improve POINT COUPLING CONDITIONS
  src/core/fem/src/discretization/4C_fem_discretization.cpp
  src/core/fem/src/dofset/4C_fem_dofset.cpp
  tests/input_files/sohex8_two-connected-pointcouplings.xml
  tests/input_files/sohex8_two-connected-pointcouplings.yaml
  tests/list_of_tests.cmake
Labels: type: enhancement

#718 Put magic_enum reflection into EnumTools namespace
  doc/documentation/src/developer_guide/codingguidelines.rst
  src/core/io/src/4C_io_input_parameter_container.hpp
  src/core/io/src/4C_io_input_parameter_container.templates.hpp
  src/core/io/src/4C_io_input_spec_builders.hpp
  src/core/io/src/4C_io_value_parser.hpp
  src/core/io/src/4C_io_yaml.hpp
  src/core/linalg/src/dense/4C_linalg_utils_densematrix_funct.hpp
  src/core/linalg/src/dense/4C_linalg_utils_tensor_interpolation.cpp
  src/core/linalg/src/dense/4C_linalg_utils_tensor_interpolation.hpp
  src/core/utils/src/stl_extension/4C_utils_enum.hpp
  src/poroelast/4C_poroelast_monolithic.cpp
  src/poroelast_scatra/4C_poroelast_scatra_monolithic.cpp
  src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.cpp
  src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic.cpp
  src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic_twoway.cpp
  src/solid_3D_ele/4C_solid_3D_ele_factory.cpp
  src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_factory.cpp
  src/structure/4C_structure_timint.cpp
  src/structure_new/src/4C_structure_new_timint_base.cpp
  src/thermo/src/implicit/4C_thermo_timint_genalpha.cpp
Labels: team: infrastructure

#712 Exodus: reorder indices for hex27
  apps/pre_exodus/4C_pre_exodus_validate.cpp
  apps/pre_exodus/4C_pre_exodus_writedat.cpp
  src/core/io/src/4C_io_exodus.cpp
  src/core/io/src/4C_io_exodus.hpp
  src/core/io/src/4C_io_meshreader.cpp
  src/global_data/4C_global_data_read.cpp
Labels: type: bug report, team: input

#702 Add runtime output to 1d arteries
  src/art_net/4C_art_net_explicitintegration.cpp
  src/art_net/4C_art_net_explicitintegration.hpp
Labels: team: output, team: reduced_fluid_models

#724 List all our CMake variables in the documentation
  doc/documentation/CMakeLists.txt
  doc/documentation/scripts/extract_cmake_variables.sh
  doc/documentation/src/developer_guide/developer_cmake.rst
  doc/documentation/src/installation/installation.rst
Labels: team: infrastructure
